package eb.gmodel1.popup;

import eb.gmodel1.generator.*;
import eb.gmodel1.investigation.*;
import eb.gmodel1.phone.*;
import eb.gmodel1.schedule.*;
import eb.gmodel1.screen.*;
import eb.gmodel1.ui.*;


import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.GlyphLayout;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer;
import com.badlogic.gdx.math.MathUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * Modal popup shown when the player taps the "Meet [client]" button.
 *
 * <h3>Layout (top → bottom)</h3>
 * <ol>
 *   <li><strong>Title bar</strong> — "Meeting: [contactName]"</li>
 *   <li><strong>Client introduction</strong> — generated by
 *       {@link ClientIntroductionGenerator} using the client's gender and
 *       personality-influenced attributes.</li>
 *   <li><strong>Detective reply</strong> — a standard acknowledgement.</li>
 *   <li><strong>Question buttons</strong> — the player taps one to ask a
 *       follow-up question; the button is then marked "ASKED".</li>
 *   <li>While questions remain unanswered: <strong>Close button</strong> —
 *       dismisses the popup (with confirmation); question progress is preserved
 *       so re-opening the popup continues where the player left off.</li>
 *   <li>Once all questions are answered: <strong>Accept / Reject buttons</strong>
 *       (separated by a divider) replace the Close button.</li>
 * </ol>
 *
 * <h3>Usage (MainScreen)</h3>
 * <pre>
 *   meetPopup.show(entry);
 *   // each frame:
 *   meetPopup.draw(screenW, screenH);
 *   // on tap:
 *   int result = meetPopup.onTap(screenX, flippedY);
 *   // result >= 0       → question index tapped
 *   // RESULT_ACCEPTED   → "Accept Case" button tapped (all questions answered)
 *   // RESULT_REJECTED   → "Reject Case" button tapped (all questions answered)
 *   // RESULT_CLOSED     → close button confirmed (questions not all answered);
 *   //                     question state is preserved for re-open
 *   // RESULT_MISS       → no interactive area hit
 * </pre>
 */
public class MeetPopup {

    /** Returned by {@link #onTap} when the close button was tapped. */
    public static final int RESULT_CLOSED   = -1;
    /** Returned by {@link #onTap} when no interactive area was hit. */
    public static final int RESULT_MISS     = -2;
    /** Returned by {@link #onTap} when the "Accept Case" button was tapped. */
    public static final int RESULT_ACCEPTED = -3;
    /** Returned by {@link #onTap} when the "Reject Case" button was tapped. */
    public static final int RESULT_REJECTED = -4;

    // ---- Colours ----
    private static final Color BG_COLOR        = new Color(0.05f, 0.08f, 0.14f, 1f);
    private static final Color BORDER_COLOR    = new Color(0.40f, 0.60f, 0.85f, 1f);
    private static final Color TITLE_COLOR     = new Color(0.80f, 0.90f, 1.00f, 1f);
    private static final Color DIVIDER_COLOR   = new Color(0.25f, 0.35f, 0.55f, 1f);
    private static final Color INTRO_LABEL_CLR = new Color(0.65f, 0.80f, 1.00f, 1f);
    private static final Color INTRO_TEXT_CLR  = new Color(0.88f, 0.88f, 0.88f, 1f);
    private static final Color REPLY_LABEL_CLR = new Color(0.50f, 1.00f, 0.65f, 1f);
    private static final Color REPLY_TEXT_CLR  = new Color(0.80f, 0.95f, 0.80f, 1f);
    private static final Color BTN_FILL        = new Color(0.12f, 0.25f, 0.42f, 1f);
    private static final Color BTN_FILL_ASKED  = new Color(0.10f, 0.30f, 0.15f, 1f);
    private static final Color BTN_BORDER      = new Color(0.35f, 0.55f, 0.80f, 1f);
    private static final Color BTN_TEXT        = new Color(0.90f, 0.90f, 0.90f, 1f);
    private static final Color BTN_ASKED_TEXT  = new Color(0.50f, 0.90f, 0.55f, 1f);
    private static final Color ANSWER_TEXT_CLR = new Color(0.85f, 0.82f, 0.65f, 1f);
    private static final Color ACCEPT_FILL     = new Color(0.10f, 0.40f, 0.15f, 1f);
    private static final Color ACCEPT_BORDER   = new Color(0.25f, 0.80f, 0.35f, 1f);
    private static final Color ACCEPT_TEXT     = new Color(0.80f, 1.00f, 0.82f, 1f);
    private static final Color REJECT_FILL     = new Color(0.40f, 0.10f, 0.10f, 1f);
    private static final Color REJECT_BORDER   = new Color(0.75f, 0.28f, 0.28f, 1f);
    private static final Color REJECT_TEXT     = new Color(0.95f, 0.90f, 0.90f, 1f);
    private static final Color CLOSE_FILL      = new Color(0.40f, 0.10f, 0.10f, 1f);
    private static final Color CLOSE_BORDER    = new Color(0.75f, 0.28f, 0.28f, 1f);
    private static final Color CLOSE_TEXT      = new Color(0.95f, 0.90f, 0.90f, 1f);

    // Confirmation overlay colours
    private static final Color CONFIRM_BG_COLOR   = new Color(0.05f, 0.08f, 0.14f, 1f);
    private static final Color CONFIRM_BORDER_CLR = new Color(0.80f, 0.70f, 0.20f, 1f);
    private static final Color CONFIRM_TEXT_CLR   = new Color(0.95f, 0.90f, 0.70f, 1f);
    private static final Color CONFIRM_YES_FILL   = new Color(0.50f, 0.10f, 0.10f, 1f);
    private static final Color CONFIRM_YES_BORDER = new Color(0.85f, 0.25f, 0.25f, 1f);
    private static final Color CONFIRM_NO_FILL    = new Color(0.10f, 0.25f, 0.42f, 1f);
    private static final Color CONFIRM_NO_BORDER  = new Color(0.35f, 0.55f, 0.80f, 1f);
    private static final Color CONFIRM_BTN_TEXT   = new Color(0.95f, 0.90f, 0.90f, 1f);

    // ---- Rendering resources ----
    private final SpriteBatch   batch;
    private final ShapeRenderer sr;
    private final BitmapFont    font;
    private final BitmapFont    smallFont;
    private final GlyphLayout   glyph;

    // ---- Popup state ----
    private boolean      visible      = false;
    private String       contactName  = "";
    private String       introText    = "";
    private String       replyText    = "";
    private List<String> questions    = new ArrayList<>();
    private boolean[]    questionAsked;
    /** Parallel list of answer texts; empty string means no answer for that question. */
    private List<String> answers      = new ArrayList<>();

    // ---- Hit-test bounds (written each frame during draw, read by onTap) ----
    private float dialogX, dialogY, dialogW, dialogH;
    private float acceptBtnX, acceptBtnY, acceptBtnW, acceptBtnH;
    private float rejectBtnX, rejectBtnY, rejectBtnW, rejectBtnH;
    private float closeBtnX, closeBtnY, closeBtnW, closeBtnH;
    private float[] qBtnX, qBtnY, qBtnW;
    private float   qBtnH;

    // ---- Confirmation-close overlay state ----
    private boolean confirmingClose = false;
    private float confirmYesBtnX, confirmYesBtnY, confirmYesBtnW, confirmYesBtnH;
    private float confirmNoBtnX,  confirmNoBtnY,  confirmNoBtnW,  confirmNoBtnH;

    // (no instance state needed for word-wrap — WordWrapper is static)

    // -------------------------------------------------------------------------

    public MeetPopup(SpriteBatch batch, ShapeRenderer sr,
              BitmapFont font, BitmapFont smallFont, GlyphLayout glyph) {
        this.batch     = batch;
        this.sr        = sr;
        this.font      = font;
        this.smallFont = smallFont;
        this.glyph     = glyph;
    }

    // -------------------------------------------------------------------------
    // State queries
    // -------------------------------------------------------------------------

    public boolean isVisible() { return visible; }

    // -------------------------------------------------------------------------
    // Commands
    // -------------------------------------------------------------------------

    /**
     * Opens the meet popup for the given calendar entry.
     *
     * <p>Personality attributes (charisma, empathy, nervousness) are derived
     * deterministically from the contact name so that the same client always
     * produces the same introduction style, while still varying per client.
     *
     * @param entry      the upcoming appointment; must not be {@code null}
     * @param caseContext short objective string from the matching {@link CaseFile}
     *                   (may be empty or {@code null})
     */
    public void show(CalendarEntry entry, String caseContext) {
        if (entry == null) return;

        String newContactName = entry.contactName.isEmpty() ? entry.title : entry.contactName;
        String gender = entry.contactGender;

        // Derive personality attributes from a stable hash of the contact name.
        int nameHash = Math.abs(newContactName.hashCode());
        int charisma    = 1 + (nameHash % 10);
        int empathy     = 1 + ((nameHash / 10) % 10);
        int nervousness = 1 + ((nameHash / 100) % 10);

        introText  = ClientIntroductionGenerator.buildIntroduction(
                newContactName, gender, charisma, empathy, nervousness, caseContext);
        replyText  = ClientIntroductionGenerator.buildDetectiveReply(newContactName);

        // Preserve question state when re-opening for the same contact so the
        // player doesn't lose their progress after using Close to step away.
        boolean sameContact = questionAsked != null
                && newContactName.equals(contactName);
        contactName = newContactName;
        if (!sameContact) {
            List<String> qs = new ArrayList<>(ClientIntroductionGenerator.buildQuestions());
            List<String> as = new ArrayList<>();
            for (int i = 0; i < qs.size(); i++) as.add("");
            initQuestionState(qs, as);
        }

        confirmingClose = false;
        visible = true;
    }

    /**
     * Opens the meet popup using a pre-generated {@link MeetingQA} dialogue list
     * from the matching {@link CaseFile}.  Each entry's question is shown as a
     * tappable button; the client's answer text is revealed below the button
     * once the player taps it.
     *
     * <p>Falls back to the generic question list when {@code dialogue} is
     * {@code null} or empty.
     *
     * @param entry    the upcoming appointment; must not be {@code null}
     * @param caseContext short objective string used for the introduction
     * @param dialogue pre-generated Q&amp;A pairs from the {@link CaseFile}
     */
    public void show(CalendarEntry entry, String caseContext, java.util.List<MeetingQA> dialogue) {
        if (entry == null) return;

        String newContactName = entry.contactName.isEmpty() ? entry.title : entry.contactName;
        String gender = entry.contactGender;

        int nameHash = Math.abs(newContactName.hashCode());
        int charisma    = 1 + (nameHash % 10);
        int empathy     = 1 + ((nameHash / 10) % 10);
        int nervousness = 1 + ((nameHash / 100) % 10);

        introText = ClientIntroductionGenerator.buildIntroduction(
                newContactName, gender, charisma, empathy, nervousness, caseContext);
        replyText = ClientIntroductionGenerator.buildDetectiveReply(newContactName);

        boolean sameContact = questionAsked != null && newContactName.equals(contactName);
        contactName = newContactName;
        if (!sameContact) {
            if (dialogue != null && !dialogue.isEmpty()) {
                List<String> qs = new ArrayList<>();
                List<String> as = new ArrayList<>();
                for (MeetingQA qa : dialogue) {
                    qs.add(qa.getQuestion());
                    as.add(qa.getAnswer());
                }
                initQuestionState(qs, as);
            } else {
                List<String> qs = new ArrayList<>(ClientIntroductionGenerator.buildQuestions());
                List<String> as = new ArrayList<>();
                for (int i = 0; i < qs.size(); i++) as.add("");
                initQuestionState(qs, as);
            }
        }

        confirmingClose = false;
        visible = true;
    }

    /** Hides the popup. */
    public void hide() { visible = false; confirmingClose = false; }

    /**
     * Initialises the question/answer/hit-test arrays from the provided lists.
     * Both lists must be the same size.
     */
    private void initQuestionState(List<String> qs, List<String> as) {
        questions     = new ArrayList<>(qs);
        answers       = new ArrayList<>(as);
        questionAsked = new boolean[questions.size()];
        qBtnX = new float[questions.size()];
        qBtnY = new float[questions.size()];
        qBtnW = new float[questions.size()];
    }

    /**
     * Returns an unmodifiable list of the question texts that were tapped
     * (asked) by the player during this meeting.  An empty list is returned
     * when the popup has never been shown or no questions were asked.
     */
    public List<String> getAskedQuestions() {
        List<String> result = new ArrayList<>();
        if (questionAsked == null) return java.util.Collections.unmodifiableList(result);
        for (int i = 0; i < questionAsked.length; i++) {
            if (questionAsked[i] && i < questions.size()) {
                result.add(questions.get(i));
            }
        }
        return java.util.Collections.unmodifiableList(result);
    }

    // -------------------------------------------------------------------------
    // Input handling
    // -------------------------------------------------------------------------

    /**
     * Handles a tap on this popup.
     *
     * @param screenX  x coordinate (screen space, 0 = left)
     * @param flippedY y coordinate (OpenGL flipped: 0 = bottom)
     * @return index (≥ 0) of the tapped question, {@link #RESULT_ACCEPTED},
     *         {@link #RESULT_REJECTED}, {@link #RESULT_CLOSED}, or
     *         {@link #RESULT_MISS}
     */
    public int onTap(int screenX, int flippedY) {
        if (!visible) return RESULT_MISS;

        // When the confirmation overlay is visible only its buttons are active.
        if (confirmingClose) {
            if (confirmYesBtnW > 0
                    && screenX >= confirmYesBtnX && screenX <= confirmYesBtnX + confirmYesBtnW
                    && flippedY >= confirmYesBtnY && flippedY <= confirmYesBtnY + confirmYesBtnH) {
                visible = false;
                confirmingClose = false;
                return RESULT_CLOSED;
            }
            if (confirmNoBtnW > 0
                    && screenX >= confirmNoBtnX && screenX <= confirmNoBtnX + confirmNoBtnW
                    && flippedY >= confirmNoBtnY && flippedY <= confirmNoBtnY + confirmNoBtnH) {
                confirmingClose = false;
            }
            return RESULT_MISS;
        }

        // Accept Case button — only active once all questions answered
        if (allQuestionsAnswered() && acceptBtnW > 0
                && screenX >= acceptBtnX && screenX <= acceptBtnX + acceptBtnW
                && flippedY >= acceptBtnY && flippedY <= acceptBtnY + acceptBtnH) {
            visible = false;
            return RESULT_ACCEPTED;
        }

        // Reject Case button — only active once all questions answered
        if (allQuestionsAnswered() && rejectBtnW > 0
                && screenX >= rejectBtnX && screenX <= rejectBtnX + rejectBtnW
                && flippedY >= rejectBtnY && flippedY <= rejectBtnY + rejectBtnH) {
            visible = false;
            return RESULT_REJECTED;
        }

        // Close button — always active
        if (closeBtnW > 0
                && screenX >= closeBtnX && screenX <= closeBtnX + closeBtnW
                && flippedY >= closeBtnY && flippedY <= closeBtnY + closeBtnH) {
            if (allQuestionsAnswered()) {
                visible = false;
                return RESULT_CLOSED;
            }
            confirmingClose = true;
            return RESULT_MISS;
        }

        // Question buttons
        if (qBtnW != null && qBtnH > 0) {
            for (int i = 0; i < questions.size(); i++) {
                if (qBtnW[i] <= 0) continue;
                if (screenX >= qBtnX[i] && screenX <= qBtnX[i] + qBtnW[i]
                        && flippedY >= qBtnY[i] && flippedY <= qBtnY[i] + qBtnH) {
                    questionAsked[i] = true;
                    return i;
                }
            }
        }

        return RESULT_MISS;
    }

    /** Returns {@code true} only when every question button has been tapped. */
    private boolean allQuestionsAnswered() {
        if (questionAsked == null) return true;
        for (boolean asked : questionAsked) {
            if (!asked) return false;
        }
        return true;
    }

    // -------------------------------------------------------------------------
    // Drawing
    // -------------------------------------------------------------------------

    /**
     * Draws the meet popup spanning the full screen width.
     * Does nothing when {@link #isVisible()} is {@code false}.
     *
     * <p>Layout (top → bottom):
     * <pre>
     *   PAD
     *   title (font)
     *   SECTION_GAP + title-divider + SECTION_GAP
     *   "Client:" label   intro text lines
     *   SECTION_GAP + divider + SECTION_GAP
     *   "You:" label   reply text lines
     *   SECTION_GAP + divider + SECTION_GAP
     *   nQ × (BTN_H + BTN_GAP)          question buttons
     *   SECTION_GAP
     *   [when questions remain]          CLOSE_H   close button
     *   [when all answered]              DIVIDER_H + SECTION_GAP + ACCEPT_H
     *                                    accept &amp; reject side by side
     *   PAD
     * </pre>
     *
     * @param screenW screen width in pixels
     * @param screenH screen height in pixels
     */
    public void draw(int screenW, int screenH) {
        if (!visible) return;

        // ---- Layout constants ----
        final float PAD         = 16f;  // inner horizontal padding and top/bottom pad
        final float LINE_GAP    = 4f;   // vertical gap between consecutive text lines
        final float SECTION_GAP = 12f;  // vertical gap between major content sections
        final float DIVIDER_H   = 1f;   // height of section-divider line
        final float BTN_GAP     = 6f;   // gap between consecutive question buttons

        // ---- Font metrics ----
        glyph.setText(font, "Hg");
        float fontH  = glyph.height;
        glyph.setText(smallFont, "Hg");
        float smallH = glyph.height;
        float lineH  = smallH + LINE_GAP;

        // Button heights are derived from the actual measured font height so
        // text is always contained inside the button on every screen density.
        final float BTN_V_PAD  = 10f;  // vertical padding above/below text inside button
        final float BTN_H      = smallH + BTN_V_PAD * 2f;  // question button height
        final float ACCEPT_H   = smallH + BTN_V_PAD * 2f;  // accept/reject row height
        final float CLOSE_H    = smallH + BTN_V_PAD * 2f;  // close button height

        boolean allAnswered = allQuestionsAnswered();

        // ---- Full-width dialog ----
        float dW    = screenW;
        float innerW = dW - PAD * 2f;
        dialogW = dW;
        dialogX = 0f;

        // ---- Word-wrap both text blocks to the inner width ----
        WordWrapper.WidthMeasurer msr = t -> {
            glyph.setText(smallFont, t);
            return glyph.width;
        };
        List<String> introLines = WordWrapper.wrap(introText, innerW, msr);
        List<String> replyLines = WordWrapper.wrap(replyText, innerW, msr);

        int nQ = questions.size();
        qBtnH = BTN_H;
        final float ANSWER_PAD = 4f;  // gap between button bottom and first answer line

        // ---- Pre-compute wrapped answer lines (needed for height and drawing) ----
        List<List<String>> answerLinesList = new ArrayList<>();
        for (int i = 0; i < nQ; i++) {
            String ans = (answers != null && i < answers.size()) ? answers.get(i) : "";
            if (questionAsked != null && questionAsked[i] && !ans.isEmpty()) {
                answerLinesList.add(WordWrapper.wrap(ans, innerW - 16f, msr));
            } else {
                answerLinesList.add(java.util.Collections.emptyList());
            }
        }

        // ---- Question block height (variable: answered questions include answer lines) ----
        float questionBlockH = 0f;
        for (int i = 0; i < nQ; i++) {
            questionBlockH += BTN_H + BTN_GAP;
            int aLines = answerLinesList.get(i).size();
            if (aLines > 0) {
                questionBlockH += ANSWER_PAD + aLines * lineH;
            }
        }

        // ---- Compute required dialog height from the layout formula ----
        float dH = PAD                                          // top pad
                + fontH + SECTION_GAP                          // title text + gap below
                + DIVIDER_H + SECTION_GAP                      // title divider + gap below
                + lineH                                        // "Client:" label
                + introLines.size() * lineH                    // intro text lines
                + SECTION_GAP                                  // gap before intro divider
                + DIVIDER_H + SECTION_GAP                      // intro/reply divider + gap below
                + lineH                                        // "You:" label
                + replyLines.size() * lineH                    // reply text lines
                + SECTION_GAP                                  // gap before reply divider
                + DIVIDER_H + SECTION_GAP                      // reply/questions divider + gap below
                + questionBlockH                               // question buttons + answer lines
                + SECTION_GAP                                  // gap before bottom row
                + PAD;                                         // bottom pad
        if (allAnswered) {
            // Accept/Reject row replaces the Close button
            dH += DIVIDER_H + SECTION_GAP + ACCEPT_H;
        } else {
            dH += CLOSE_H;
        }

        // Never taller than the screen; never shorter than 240px or half the screen height.
        dH = MathUtils.clamp(dH, Math.max(240f, screenH * 0.50f), (float) screenH);
        dialogH = dH;
        dialogY = (screenH - dH) / 2f;

        // ---- Top-down position tracking ----
        // 'curY' is the Y of the TOP of the next element to be placed.
        // In libGDX Y=0 is at the screen bottom, so curY decreases as we move
        // visually downward.  For text: font.draw(batch, text, x, curY) places
        // the text top at curY; the glyph extends downward to curY-smallH.
        // For button rects: qBtnY[i] = curY - BTN_H (the rect's bottom edge).
        float curY = dialogY + dH - PAD;

        // Title
        float titleY = curY;
        curY -= fontH + SECTION_GAP;

        // Title divider
        float titleDivY = curY;
        curY -= DIVIDER_H + SECTION_GAP;

        // "Client:" label
        float introLabelY = curY;
        curY -= lineH;

        // Intro text lines
        float[] introLineY = new float[introLines.size()];
        for (int i = 0; i < introLines.size(); i++) {
            introLineY[i] = curY;
            curY -= lineH;
        }
        curY -= SECTION_GAP;

        // Intro / reply divider
        float introDivY = curY;
        curY -= DIVIDER_H + SECTION_GAP;

        // "You:" label
        float replyLabelY = curY;
        curY -= lineH;

        // Reply text lines
        float[] replyLineY = new float[replyLines.size()];
        for (int i = 0; i < replyLines.size(); i++) {
            replyLineY[i] = curY;
            curY -= lineH;
        }
        curY -= SECTION_GAP;

        // Reply / questions divider
        float replyDivY = curY;
        curY -= DIVIDER_H + SECTION_GAP;

        // Question buttons (rect bottom = curY - BTN_H) + answer lines below each answered button
        float[] answerStartY = new float[nQ];
        for (int i = 0; i < nQ; i++) {
            qBtnY[i] = curY - BTN_H;
            qBtnX[i] = dialogX + PAD;
            qBtnW[i] = innerW;
            curY -= BTN_H + BTN_GAP;
            int aLines = answerLinesList.get(i).size();
            if (aLines > 0) {
                answerStartY[i] = curY - ANSWER_PAD;
                curY -= ANSWER_PAD + aLines * lineH;
            } else {
                answerStartY[i] = 0f;
            }
        }
        curY -= SECTION_GAP;

        // Accept / Reject buttons — only when all questions answered
        float acceptRejectDivY = 0f;
        if (allAnswered) {
            acceptRejectDivY = curY;
            curY -= DIVIDER_H + SECTION_GAP;

            final float ACTION_BTN_GAP = 8f;
            float halfW = (innerW - ACTION_BTN_GAP) / 2f;
            acceptBtnY = curY - ACCEPT_H;
            acceptBtnX = dialogX + PAD;
            acceptBtnW = halfW;
            acceptBtnH = ACCEPT_H;

            rejectBtnY = curY - ACCEPT_H;
            rejectBtnX = dialogX + PAD + halfW + ACTION_BTN_GAP;
            rejectBtnW = halfW;
            rejectBtnH = ACCEPT_H;
            // no curY advance needed — PAD below covers the bottom gap
        } else {
            acceptBtnW = 0f;
            rejectBtnW = 0f;
        }

        // Close button — only shown when Accept/Reject are NOT yet available
        if (!allAnswered) {
            closeBtnY = curY - CLOSE_H;
            closeBtnX = dialogX + PAD;
            closeBtnW = innerW;
            closeBtnH = CLOSE_H;
        } else {
            closeBtnW = 0f;
        }

        // ---- Shapes: filled ----
        sr.begin(ShapeRenderer.ShapeType.Filled);

        sr.setColor(BG_COLOR);
        sr.rect(dialogX, dialogY, dW, dH);

        for (int i = 0; i < nQ; i++) {
            sr.setColor(questionAsked[i] ? BTN_FILL_ASKED : BTN_FILL);
            sr.rect(qBtnX[i], qBtnY[i], innerW, BTN_H);
        }

        if (allAnswered) {
            sr.setColor(ACCEPT_FILL);
            sr.rect(acceptBtnX, acceptBtnY, acceptBtnW, acceptBtnH);
            sr.setColor(REJECT_FILL);
            sr.rect(rejectBtnX, rejectBtnY, rejectBtnW, rejectBtnH);
        } else {
            sr.setColor(CLOSE_FILL);
            sr.rect(closeBtnX, closeBtnY, closeBtnW, closeBtnH);
        }

        sr.end();

        // ---- Shapes: borders and dividers ----
        sr.begin(ShapeRenderer.ShapeType.Line);

        sr.setColor(BORDER_COLOR);
        sr.rect(dialogX,     dialogY,     dW,     dH);
        sr.rect(dialogX + 1, dialogY + 1, dW - 2, dH - 2);

        sr.setColor(DIVIDER_COLOR);
        sr.line(dialogX + PAD, titleDivY, dialogX + dW - PAD, titleDivY);
        sr.line(dialogX + PAD, introDivY, dialogX + dW - PAD, introDivY);
        sr.line(dialogX + PAD, replyDivY, dialogX + dW - PAD, replyDivY);
        if (allAnswered) {
            sr.line(dialogX + PAD, acceptRejectDivY, dialogX + dW - PAD, acceptRejectDivY);
            sr.setColor(ACCEPT_BORDER);
            sr.rect(acceptBtnX, acceptBtnY, acceptBtnW, acceptBtnH);
            sr.setColor(REJECT_BORDER);
            sr.rect(rejectBtnX, rejectBtnY, rejectBtnW, rejectBtnH);
        } else {
            sr.setColor(CLOSE_BORDER);
            sr.rect(closeBtnX, closeBtnY, closeBtnW, closeBtnH);
        }

        for (int i = 0; i < nQ; i++) {
            if (qBtnW[i] > 0) {
                sr.setColor(BTN_BORDER);
                sr.rect(qBtnX[i], qBtnY[i], qBtnW[i], BTN_H);
            }
        }

        sr.end();

        // ---- Text ----
        batch.begin();

        // Title — centred horizontally
        String titleStr = "Meeting: " + contactName;
        glyph.setText(font, titleStr);
        font.setColor(TITLE_COLOR);
        font.draw(batch, titleStr, dialogX + dW / 2f - glyph.width / 2f, titleY);

        // "Client:" label
        smallFont.setColor(INTRO_LABEL_CLR);
        smallFont.draw(batch, contactName + ":", dialogX + PAD, introLabelY);

        // Intro text lines
        smallFont.setColor(INTRO_TEXT_CLR);
        for (int i = 0; i < introLines.size(); i++) {
            smallFont.draw(batch, introLines.get(i), dialogX + PAD, introLineY[i]);
        }

        // "You:" label
        smallFont.setColor(REPLY_LABEL_CLR);
        smallFont.draw(batch, "You:", dialogX + PAD, replyLabelY);

        // Reply text lines
        smallFont.setColor(REPLY_TEXT_CLR);
        for (int i = 0; i < replyLines.size(); i++) {
            smallFont.draw(batch, replyLines.get(i), dialogX + PAD, replyLineY[i]);
        }

        // Question button labels — vertically centred inside each button;
        // answer text shown below each button once it has been tapped
        for (int i = 0; i < nQ; i++) {
            if (qBtnW[i] <= 0) continue;
            String label   = questions.get(i);
            String display = questionAsked[i] ? "\u2713 " + label : label;
            glyph.setText(smallFont, display);
            smallFont.setColor(questionAsked[i] ? BTN_ASKED_TEXT : BTN_TEXT);
            float ty = qBtnY[i] + (BTN_H + glyph.height) / 2f;
            smallFont.draw(batch, display, qBtnX[i] + 8f, ty);

            // Draw the client's answer below the button once the question is asked
            List<String> aLines = answerLinesList.get(i);
            if (!aLines.isEmpty()) {
                float ay = answerStartY[i];
                smallFont.setColor(ANSWER_TEXT_CLR);
                for (String line : aLines) {
                    smallFont.draw(batch, line, qBtnX[i] + 16f, ay);
                    ay -= lineH;
                }
            }
        }

        // Accept / Reject button labels — only when all questions answered;
        // Close button label — only when Accept/Reject not yet available
        if (allAnswered) {
            glyph.setText(smallFont, "Accept Case");
            smallFont.setColor(ACCEPT_TEXT);
            smallFont.draw(batch, "Accept Case",
                    acceptBtnX + (acceptBtnW - glyph.width) / 2f,
                    acceptBtnY + (acceptBtnH + glyph.height) / 2f);

            glyph.setText(smallFont, "Reject Case");
            smallFont.setColor(REJECT_TEXT);
            smallFont.draw(batch, "Reject Case",
                    rejectBtnX + (rejectBtnW - glyph.width) / 2f,
                    rejectBtnY + (rejectBtnH + glyph.height) / 2f);
        } else {
            glyph.setText(smallFont, "Close");
            smallFont.setColor(CLOSE_TEXT);
            smallFont.draw(batch, "Close",
                    closeBtnX + closeBtnW / 2f - glyph.width / 2f,
                    closeBtnY + (closeBtnH + glyph.height) / 2f);
        }

        batch.end();

        // ---- Confirmation overlay (drawn on top when confirmingClose is true) ----
        if (confirmingClose) {
            drawConfirmationOverlay(screenW, screenH, fontH, smallH);
        }
    }

    /**
     * Draws the "Close without finishing?" confirmation overlay centred on screen.
     * Also writes the hit-test bounds for the Yes/No buttons so {@link #onTap}
     * can read them on the next input event.
     */
    private void drawConfirmationOverlay(int screenW, int screenH,
                                         float fontH, float smallH) {
        final String CONFIRM_MSG = "Close without finishing?";
        final String YES_LABEL   = "Yes, Close";
        final String NO_LABEL    = "Keep Going";

        final float CP_PAD     = 20f;
        final float CP_BTN_VP  = 10f;
        final float CP_BTN_H   = smallH + CP_BTN_VP * 2f;
        final float CP_BTN_GAP = 12f;

        glyph.setText(font, CONFIRM_MSG);
        float msgW  = glyph.width;
        glyph.setText(smallFont, YES_LABEL);
        float yesTW = glyph.width;
        glyph.setText(smallFont, NO_LABEL);
        float noTW  = glyph.width;

        float yesBW    = Math.max(yesTW + CP_PAD * 2f, 120f);
        float noBW     = Math.max(noTW  + CP_PAD * 2f, 120f);
        float btnsRowW = yesBW + CP_BTN_GAP + noBW;
        float panelW   = Math.max(msgW, btnsRowW) + CP_PAD * 2f;
        float panelH   = CP_PAD + fontH + CP_PAD + CP_BTN_H + CP_PAD;
        float panelX   = (screenW - panelW) / 2f;
        float panelY   = (screenH - panelH) / 2f;

        float btnsStartX = panelX + (panelW - btnsRowW) / 2f;
        float btnsY      = panelY + CP_PAD;

        confirmYesBtnX = btnsStartX;
        confirmYesBtnY = btnsY;
        confirmYesBtnW = yesBW;
        confirmYesBtnH = CP_BTN_H;

        confirmNoBtnX = btnsStartX + yesBW + CP_BTN_GAP;
        confirmNoBtnY = btnsY;
        confirmNoBtnW = noBW;
        confirmNoBtnH = CP_BTN_H;

        sr.begin(ShapeRenderer.ShapeType.Filled);
        sr.setColor(CONFIRM_BG_COLOR);
        sr.rect(panelX, panelY, panelW, panelH);
        sr.setColor(CONFIRM_YES_FILL);
        sr.rect(confirmYesBtnX, confirmYesBtnY, confirmYesBtnW, confirmYesBtnH);
        sr.setColor(CONFIRM_NO_FILL);
        sr.rect(confirmNoBtnX, confirmNoBtnY, confirmNoBtnW, confirmNoBtnH);
        sr.end();

        sr.begin(ShapeRenderer.ShapeType.Line);
        sr.setColor(CONFIRM_BORDER_CLR);
        sr.rect(panelX,     panelY,     panelW,     panelH);
        sr.rect(panelX + 1, panelY + 1, panelW - 2, panelH - 2);
        sr.setColor(CONFIRM_YES_BORDER);
        sr.rect(confirmYesBtnX, confirmYesBtnY, confirmYesBtnW, confirmYesBtnH);
        sr.setColor(CONFIRM_NO_BORDER);
        sr.rect(confirmNoBtnX, confirmNoBtnY, confirmNoBtnW, confirmNoBtnH);
        sr.end();

        batch.begin();
        font.setColor(CONFIRM_TEXT_CLR);
        font.draw(batch, CONFIRM_MSG,
                panelX + panelW / 2f - msgW / 2f,
                panelY + panelH - CP_PAD);
        glyph.setText(smallFont, YES_LABEL);
        smallFont.setColor(CONFIRM_BTN_TEXT);
        smallFont.draw(batch, YES_LABEL,
                confirmYesBtnX + (confirmYesBtnW - glyph.width) / 2f,
                confirmYesBtnY + (confirmYesBtnH + glyph.height) / 2f);
        glyph.setText(smallFont, NO_LABEL);
        smallFont.setColor(CONFIRM_BTN_TEXT);
        smallFont.draw(batch, NO_LABEL,
                confirmNoBtnX + (confirmNoBtnW - glyph.width) / 2f,
                confirmNoBtnY + (confirmNoBtnH + glyph.height) / 2f);
        batch.end();
    }
}
