package eb.framework1.popup;

import eb.framework1.character.NpcCharacter;
import eb.framework1.character.PersonDescriptionEngine;
import eb.framework1.generator.WordWrapper;
import eb.framework1.ui.InfoPanelRenderer;
import eb.framework1.ui.TextMeasurer;


import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.GlyphLayout;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer;
import com.badlogic.gdx.Gdx;

import java.util.List;

/**
 * Modal popup that shows the result of examining an unknown person from afar.
 *
 * <p>The description is generated by {@link PersonDescriptionEngine} from the NPC's
 * observable appearance attributes (hair type/colour, apparent wealth, favourite colour).
 * The popup never reveals private information such as the NPC's name or occupation.
 *
 * <h3>Usage</h3>
 * <pre>{@code
 * // Construct once
 * ExaminePersonPopup popup = new ExaminePersonPopup(batch, sr, font, smallFont, glyph);
 *
 * // Open when the player taps an eye icon
 * popup.show(npc);
 *
 * // Each frame — inside render()
 * if (popup.isVisible()) popup.draw(screenW, screenH);
 *
 * // On tap — inside touchUp
 * if (popup.isVisible()) popup.onTap(screenX, flippedY);
 * }</pre>
 */
public class ExaminePersonPopup {

    // -------------------------------------------------------------------------
    // Colours
    // -------------------------------------------------------------------------

    private static final Color BG_COLOR       = new Color(0.07f, 0.09f, 0.16f, 1f);
    private static final Color BORDER_COLOR   = new Color(0.55f, 0.70f, 0.90f, 1f);
    private static final Color TITLE_COLOR    = new Color(0.85f, 0.92f, 1.00f, 1f);
    private static final Color CLOSE_BTN_COLOR = new Color(0.25f, 0.10f, 0.35f, 1f);

    // -------------------------------------------------------------------------
    // Rendering resources
    // -------------------------------------------------------------------------

    private final SpriteBatch   batch;
    private final ShapeRenderer sr;
    private final BitmapFont    font;
    private final BitmapFont    smallFont;
    private final GlyphLayout   glyph;

    // -------------------------------------------------------------------------
    // State
    // -------------------------------------------------------------------------

    private boolean      visible = false;
    private NpcCharacter npc     = null;
    /** Pre-generated description lines for the current NPC. */
    private List<String> descLines = java.util.Collections.emptyList();

    // Hit areas — written during draw(), read by onTap()
    private float closeBtnX, closeBtnY, closeBtnW, closeBtnH;

    // -------------------------------------------------------------------------
    // Constructor
    // -------------------------------------------------------------------------

    public ExaminePersonPopup(SpriteBatch batch, ShapeRenderer sr,
                               BitmapFont font, BitmapFont smallFont, GlyphLayout glyph) {
        this.batch     = batch;
        this.sr        = sr;
        this.font      = font;
        this.smallFont = smallFont;
        this.glyph     = glyph;
    }

    // -------------------------------------------------------------------------
    // Public API
    // -------------------------------------------------------------------------

    /** Returns {@code true} while the popup is open. */
    public boolean isVisible() { return visible; }

    /**
     * Opens the popup showing the visual description of {@code npc}.
     *
     * @param npc the character to examine; must not be {@code null}
     */
    public void show(NpcCharacter npc) {
        if (npc == null) return;
        this.npc     = npc;
        this.visible = true;
        this.closeBtnW = 0f;
        Gdx.app.log("ExaminePersonPopup", "Showing examination for NPC " + npc.getId());
    }

    /** Closes the popup. */
    public void dismiss() {
        visible = false;
        npc     = null;
        descLines = java.util.Collections.emptyList();
    }

    /**
     * Handles a tap.  If the Close button is tapped the popup is dismissed.
     *
     * @param screenX  tap x in screen pixels (left origin)
     * @param flippedY tap y in screen pixels (bottom origin, libGDX y-up)
     */
    public void onTap(int screenX, int flippedY) {
        if (!visible || closeBtnW <= 0f) return;
        if (screenX >= closeBtnX && screenX <= closeBtnX + closeBtnW
                && flippedY >= closeBtnY && flippedY <= closeBtnY + closeBtnH) {
            dismiss();
        }
    }

    /**
     * Draws the popup centred on screen.
     *
     * <p>Must be called with neither the {@link SpriteBatch} nor the
     * {@link ShapeRenderer} active.
     *
     * @param screenW screen width in pixels
     * @param screenH screen height in pixels
     */
    public void draw(int screenW, int screenH) {
        if (!visible || npc == null) return;

        final float PAD       = 18f;
        final float GAP       = 8f;
        final float BTN_PAD_H = 28f;
        final float BTN_PAD_V = 10f;

        // ── Font metrics ──────────────────────────────────────────────────────
        glyph.setText(font, "Hg");
        float fontCapH  = glyph.height;
        float fontLineH = fontCapH * 1.4f;

        glyph.setText(smallFont, "Hg");
        float smallCapH  = glyph.height;
        float smallLineH = smallCapH * 1.35f;

        // ── Popup geometry ────────────────────────────────────────────────────
        float dialogW = screenW * 0.88f;
        float wrapW   = dialogW - 2f * PAD;

        // Re-wrap description each frame (cheap since descLines is cached until next show())
        if (descLines.isEmpty() && npc != null) {
            String raw = PersonDescriptionEngine.describe(npc);
            WordWrapper.WidthMeasurer m = t -> {
                glyph.setText(smallFont, t);
                return glyph.width;
            };
            descLines = WordWrapper.wrap(raw, wrapW, m);
        }

        TextMeasurer.TextBounds closeBounds =
                TextMeasurer.measure(font, glyph, "Close", BTN_PAD_H, BTN_PAD_V);
        float cBtnW = closeBounds.width;
        float cBtnH = closeBounds.height;

        float descH = descLines.size() * smallLineH;
        float dialogH = PAD
                + fontLineH            // title
                + GAP + descH          // description lines
                + GAP + cBtnH          // Close button
                + PAD;

        float dialogX = (screenW - dialogW) / 2f;
        float dialogY = (screenH - dialogH) / 2f;

        float closeBtnX_ = dialogX + (dialogW - cBtnW) / 2f;
        float closeBtnY_ = dialogY + PAD;

        // Store hit area
        closeBtnX = closeBtnX_; closeBtnY = closeBtnY_; closeBtnW = cBtnW; closeBtnH = cBtnH;

        // ── ShapeRenderer: background + Close button ──────────────────────────
        sr.begin(ShapeRenderer.ShapeType.Filled);
        sr.setColor(BG_COLOR);
        sr.rect(dialogX, dialogY, dialogW, dialogH);
        sr.setColor(CLOSE_BTN_COLOR);
        sr.rect(closeBtnX, closeBtnY, closeBtnW, closeBtnH);
        sr.end();

        sr.begin(ShapeRenderer.ShapeType.Line);
        sr.setColor(BORDER_COLOR);
        sr.rect(dialogX,     dialogY,     dialogW,     dialogH);
        sr.rect(dialogX + 1, dialogY + 1, dialogW - 2, dialogH - 2);
        sr.rect(closeBtnX,     closeBtnY,     closeBtnW,     closeBtnH);
        sr.rect(closeBtnX + 1, closeBtnY + 1, closeBtnW - 2, closeBtnH - 2);
        sr.end();

        // ── SpriteBatch: text ─────────────────────────────────────────────────
        batch.begin();

        // Title
        String title = "Observing from a distance...";
        glyph.setText(font, title);
        font.setColor(TITLE_COLOR);
        font.draw(batch, title,
                dialogX + (dialogW - glyph.width) / 2f,
                dialogY + dialogH - PAD);

        // Description lines (scissor-clipped just to the text area for safety)
        float textAreaBottom = closeBtnY_ + cBtnH + GAP;
        Gdx.gl.glEnable(GL20.GL_SCISSOR_TEST);
        Gdx.gl.glScissor((int) dialogX, (int) textAreaBottom,
                         (int) dialogW, (int)(dialogH - PAD - fontLineH - GAP));

        float ty = dialogY + dialogH - PAD - fontLineH - GAP;
        smallFont.setColor(InfoPanelRenderer.NOVEL_COLOR);
        for (String line : descLines) {
            smallFont.draw(batch, line, dialogX + PAD, ty);
            ty -= smallLineH;
        }

        Gdx.gl.glDisable(GL20.GL_SCISSOR_TEST);

        // Close button text (outside scissor — always visible)
        font.setColor(Color.WHITE);
        glyph.setText(font, "Close");
        font.draw(batch, "Close",
                closeBtnX + (closeBtnW - glyph.width) / 2f,
                closeBtnY + (closeBtnH + glyph.height) / 2f);

        batch.end();
    }
}
