package eb.framework1;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Represents a case file in the game.  Each case tracks clues and evidence
 * gathered by the player during an investigation.  Multiple cases may be open
 * at the same time.
 *
 * <p>Cases generated by {@link CaseGenerator} carry additional context fields:
 * the {@link CaseType}, the client who hired the detective, the subject of the
 * investigation, a clear objective statement, a list of {@link CaseLead}s —
 * hidden facts the player must uncover to solve the case — a
 * <em>complexity</em> level (1–3, hidden from the player) that controls how
 * many plot twists the investigation contains (1 = none, 2 = one, 3 = two),
 * and a {@link CaseStoryNode} <em>story tree</em> that maps every step of the
 * investigation as a four-level hierarchy (plot-twist phases → major milestones
 * → minor tasks → leaf actions).
 */
public class CaseFile {

    /** Possible statuses for a case. */
    public enum Status {
        OPEN, CLOSED, COLD
    }

    private final String id;
    private String name;
    private String description;
    private Status status;
    private String dateOpened;
    private String dateClosed;
    private final List<String>       clues;
    private final List<String>       evidence;
    private final List<String>       notes;
    private final List<EvidenceItem> evidenceItems;

    // ---- Fields populated by CaseGenerator ----
    /** Broad category of the case (nullable for legacy/manual cases). */
    private CaseType caseType;
    /** Name of the client who hired the detective. */
    private String clientName;
    /** Name of the person or entity being investigated. */
    private String subjectName;
    /**
     * One-sentence statement of what the player must find out or prove to
     * resolve the case (the client's ask).
     */
    private String objective;
    /** Hidden facts the player must uncover. */
    private final List<CaseLead> leads;
    /**
     * Hidden complexity of the case (not shown to the player).
     * <ul>
     *   <li>1 — straightforward, no plot twists</li>
     *   <li>2 — one plot twist during the investigation</li>
     *   <li>3 — two plot twists during the investigation</li>
     * </ul>
     */
    private int complexity;
    /**
     * Root of the story-progression tree.  {@code null} for legacy / manually
     * created cases.  Populated by {@link CaseGenerator}.
     */
    private CaseStoryNode storyRoot;

    /**
     * Creates a new open case file with a generated id and no clues or evidence.
     *
     * @param name        short name of the case (shown in the poplist)
     * @param description longer summary of the case
     * @param dateOpened  in-game date/time when the case was opened
     */
    public CaseFile(String name, String description, String dateOpened) {
        this(UUID.randomUUID().toString(), name, description, Status.OPEN, dateOpened, null,
                new ArrayList<>(), new ArrayList<>(), new ArrayList<>(), new ArrayList<>());
    }

    /**
     * Full constructor — used mainly when restoring a case from a save file.
     */
    public CaseFile(String id, String name, String description, Status status,
                    String dateOpened, String dateClosed, List<String> clues,
                    List<String> evidence, List<String> notes) {
        this(id, name, description, status, dateOpened, dateClosed, clues, evidence, notes,
                new ArrayList<>());
    }

    /**
     * Full constructor including physical evidence items — used mainly when
     * restoring a case from a save file.
     */
    public CaseFile(String id, String name, String description, Status status,
                    String dateOpened, String dateClosed, List<String> clues,
                    List<String> evidence, List<String> notes,
                    List<EvidenceItem> evidenceItems) {
        if (name == null || name.trim().isEmpty()) {
            throw new IllegalArgumentException("Case name cannot be null or empty");
        }
        this.id          = id != null ? id : UUID.randomUUID().toString();
        this.name        = name;
        this.description = description != null ? description : "";
        this.status      = status != null ? status : Status.OPEN;
        this.dateOpened   = dateOpened != null ? dateOpened : "";
        this.dateClosed   = dateClosed;
        this.clues         = clues != null ? new ArrayList<>(clues) : new ArrayList<>();
        this.evidence      = evidence != null ? new ArrayList<>(evidence) : new ArrayList<>();
        this.notes         = notes != null ? new ArrayList<>(notes) : new ArrayList<>();
        this.evidenceItems = evidenceItems != null ? new ArrayList<>(evidenceItems) : new ArrayList<>();
        // Generator-populated fields default to empty/null
        this.caseType    = null;
        this.clientName  = "";
        this.subjectName = "";
        this.objective   = "";
        this.leads       = new ArrayList<>();
        this.complexity  = 1;
        this.storyRoot   = null;
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public String getId()          { return id; }
    public String getName()        { return name; }
    public String getDescription() { return description; }
    public Status getStatus()      { return status; }
    public String getDateOpened()  { return dateOpened; }
    public String getDateClosed()  { return dateClosed; }

    public void setName(String name)               { this.name = name; }
    public void setDescription(String description) { this.description = description; }
    public void setDateOpened(String dateOpened)    { this.dateOpened = dateOpened; }

    // ---- Generator-populated fields ----

    /** Returns the broad category of this case, or {@code null} for legacy/manual cases. */
    public CaseType getCaseType() { return caseType; }
    /** Sets the case category (called by {@link CaseGenerator}). */
    public void setCaseType(CaseType caseType) { this.caseType = caseType; }

    /** Name of the client who hired the detective (empty string if not set). */
    public String getClientName() { return clientName; }
    /** Sets the client name. */
    public void setClientName(String clientName) {
        this.clientName = clientName != null ? clientName : "";
    }

    /** Name of the person or entity being investigated (empty string if not set). */
    public String getSubjectName() { return subjectName; }
    /** Sets the subject name. */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName != null ? subjectName : "";
    }

    /**
     * One-sentence statement of what the player must find out or prove to
     * resolve the case (the client's ask).  Empty string if not set.
     */
    public String getObjective() { return objective; }
    /** Sets the case objective. */
    public void setObjective(String objective) {
        this.objective = objective != null ? objective : "";
    }

    /**
     * Returns the hidden complexity of the case (1–3).
     * <ul>
     *   <li>1 — straightforward, no plot twists</li>
     *   <li>2 — one plot twist during the investigation</li>
     *   <li>3 — two plot twists during the investigation</li>
     * </ul>
     * This value is not shown to the player.
     */
    public int getComplexity() { return complexity; }

    /**
     * Sets the hidden complexity of the case.
     *
     * @param complexity must be 1, 2, or 3
     * @throws IllegalArgumentException if the value is outside the 1–3 range
     */
    public void setComplexity(int complexity) {
        if (complexity < 1 || complexity > 3) {
            throw new IllegalArgumentException("complexity must be 1, 2, or 3 but was " + complexity);
        }
        this.complexity = complexity;
    }

    /**
     * Returns the root of the story-progression tree, or {@code null} for
     * legacy / manually created cases that have no generated story tree.
     *
     * <p>The root node has type {@link CaseStoryNode.NodeType#ROOT}; its
     * children are the {@link CaseStoryNode.NodeType#PLOT_TWIST} phase nodes.
     */
    public CaseStoryNode getStoryRoot() { return storyRoot; }

    /**
     * Sets the story-progression tree root.  Called by {@link CaseGenerator};
     * pass {@code null} to clear the tree.
     */
    public void setStoryRoot(CaseStoryNode storyRoot) { this.storyRoot = storyRoot; }

    /** Returns an unmodifiable view of the clues recorded against this case. */
    public List<String> getClues() {
        return Collections.unmodifiableList(clues);
    }

    /** Returns an unmodifiable view of the evidence recorded against this case. */
    public List<String> getEvidence() {
        return Collections.unmodifiableList(evidence);
    }

    /** Returns an unmodifiable view of the player notes recorded against this case. */
    public List<String> getNotes() {
        return Collections.unmodifiableList(notes);
    }

    /**
     * Returns an unmodifiable view of the physical {@link EvidenceItem}s
     * collected for this case.
     */
    public List<EvidenceItem> getEvidenceItems() {
        return Collections.unmodifiableList(evidenceItems);
    }

    /**
     * Returns an unmodifiable list of physical evidence items that have at
     * least one analysis submitted.
     */
    public List<EvidenceItem> getSubmittedEvidenceItems() {
        return evidenceItems.stream()
                .filter(item -> !item.getSubmittedModifiers().isEmpty())
                .collect(Collectors.toList());
    }

    /**
     * Returns an unmodifiable view of the hidden {@link CaseLead}s attached to
     * this case.
     */
    public List<CaseLead> getLeads() {
        return Collections.unmodifiableList(leads);
    }

    /**
     * Returns an unmodifiable list of leads that the player has already
     * uncovered (i.e. {@link CaseLead#isDiscovered()} is {@code true}).
     */
    public List<CaseLead> getDiscoveredLeads() {
        return leads.stream()
                .filter(CaseLead::isDiscovered)
                .collect(Collectors.toList());
    }

    /**
     * Returns an unmodifiable list of leads that the player has not yet
     * uncovered.
     */
    public List<CaseLead> getUndiscoveredLeads() {
        return leads.stream()
                .filter(l -> !l.isDiscovered())
                .collect(Collectors.toList());
    }

    // -------------------------------------------------------------------------
    // Mutation helpers
    // -------------------------------------------------------------------------

    /** Adds a clue to this case. */
    public void addClue(String clue) {
        if (clue != null && !clue.trim().isEmpty()) {
            clues.add(clue);
        }
    }

    /** Adds a piece of evidence to this case. */
    public void addEvidence(String item) {
        if (item != null && !item.trim().isEmpty()) {
            evidence.add(item);
        }
    }

    /**
     * Adds a physical {@link EvidenceItem} to this case.
     *
     * @param item the item to add; must not be {@code null}
     * @throws IllegalArgumentException if {@code item} is {@code null}
     */
    public void addEvidenceItem(EvidenceItem item) {
        if (item == null) {
            throw new IllegalArgumentException("Evidence item must not be null");
        }
        evidenceItems.add(item);
    }

    /**
     * Attaches a hidden {@link CaseLead} to this case.
     *
     * @param lead the lead to add; must not be {@code null}
     * @throws IllegalArgumentException if {@code lead} is {@code null}
     */
    public void addLead(CaseLead lead) {
        if (lead == null) {
            throw new IllegalArgumentException("CaseLead must not be null");
        }
        leads.add(lead);
    }

    /** Adds a player note to this case. */
    public void addNote(String note) {
        if (note != null && !note.trim().isEmpty()) {
            notes.add(note);
        }
    }

    /** Closes the case and records the closing date. */
    public void close(String dateClosed) {
        this.status = Status.CLOSED;
        this.dateClosed = dateClosed;
    }

    /** Marks the case as cold (inactive but not solved). */
    public void markCold() {
        this.status = Status.COLD;
    }

    /** Re-opens a closed or cold case. */
    public void reopen() {
        this.status = Status.OPEN;
        this.dateClosed = null;
    }

    /** Returns true when the case status is {@link Status#OPEN}. */
    public boolean isOpen() {
        return status == Status.OPEN;
    }

    @Override
    public String toString() {
        return "CaseFile{name='" + name + "', status=" + status + ", clues=" + clues.size() + ", evidence=" + evidence.size() + ", notes=" + notes.size() + "}";
    }
}
