package eb.framework1;

import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.GlyphLayout;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer;
import com.badlogic.gdx.math.MathUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * Modal popup shown when the player taps the "Meet [client]" button.
 *
 * <h3>Layout (top → bottom)</h3>
 * <ol>
 *   <li><strong>Title bar</strong> — "Meeting: [contactName]"</li>
 *   <li><strong>Client introduction</strong> — generated by
 *       {@link ClientIntroductionGenerator} using the client's gender and
 *       personality-influenced attributes.</li>
 *   <li><strong>Detective reply</strong> — a standard acknowledgement.</li>
 *   <li><strong>Question buttons</strong> — the player taps one to ask a
 *       follow-up question; the button is then marked "ASKED".</li>
 *   <li><strong>Close button</strong> — dismisses the popup.</li>
 * </ol>
 *
 * <h3>Usage (MainScreen)</h3>
 * <pre>
 *   meetPopup.show(entry);
 *   // each frame:
 *   meetPopup.draw(screenW, screenH);
 *   // on tap:
 *   int result = meetPopup.onTap(screenX, flippedY);
 *   // result >= 0  → question index tapped
 *   // RESULT_CLOSED → close button tapped
 *   // RESULT_MISS   → no interactive area hit
 * </pre>
 */
class MeetPopup {

    /** Returned by {@link #onTap} when the close button was tapped. */
    static final int RESULT_CLOSED = -1;
    /** Returned by {@link #onTap} when no interactive area was hit. */
    static final int RESULT_MISS   = -2;

    // ---- Colours ----
    private static final Color BG_COLOR        = new Color(0.05f, 0.08f, 0.14f, 1f);
    private static final Color BORDER_COLOR    = new Color(0.40f, 0.60f, 0.85f, 1f);
    private static final Color TITLE_COLOR     = new Color(0.80f, 0.90f, 1.00f, 1f);
    private static final Color DIVIDER_COLOR   = new Color(0.25f, 0.35f, 0.55f, 1f);
    private static final Color INTRO_LABEL_CLR = new Color(0.65f, 0.80f, 1.00f, 1f);
    private static final Color INTRO_TEXT_CLR  = new Color(0.88f, 0.88f, 0.88f, 1f);
    private static final Color REPLY_LABEL_CLR = new Color(0.50f, 1.00f, 0.65f, 1f);
    private static final Color REPLY_TEXT_CLR  = new Color(0.80f, 0.95f, 0.80f, 1f);
    private static final Color BTN_FILL        = new Color(0.12f, 0.25f, 0.42f, 1f);
    private static final Color BTN_FILL_ASKED  = new Color(0.10f, 0.30f, 0.15f, 1f);
    private static final Color BTN_BORDER      = new Color(0.35f, 0.55f, 0.80f, 1f);
    private static final Color BTN_TEXT        = new Color(0.90f, 0.90f, 0.90f, 1f);
    private static final Color BTN_ASKED_TEXT  = new Color(0.50f, 0.90f, 0.55f, 1f);
    private static final Color CLOSE_FILL      = new Color(0.40f, 0.10f, 0.10f, 1f);
    private static final Color CLOSE_BORDER    = new Color(0.75f, 0.28f, 0.28f, 1f);
    private static final Color CLOSE_TEXT      = new Color(0.95f, 0.90f, 0.90f, 1f);

    // ---- Rendering resources ----
    private final SpriteBatch   batch;
    private final ShapeRenderer sr;
    private final BitmapFont    font;
    private final BitmapFont    smallFont;
    private final GlyphLayout   glyph;

    // ---- Popup state ----
    private boolean      visible      = false;
    private String       contactName  = "";
    private String       introText    = "";
    private String       replyText    = "";
    private List<String> questions    = new ArrayList<>();
    private boolean[]    questionAsked;

    // ---- Hit-test bounds (written each frame during draw, read by onTap) ----
    private float dialogX, dialogY, dialogW, dialogH;
    private float closeBtnX, closeBtnY, closeBtnW, closeBtnH;
    private float[] qBtnX, qBtnY, qBtnW;
    private float   qBtnH;

    // (no instance state needed for word-wrap — WordWrapper is static)

    // -------------------------------------------------------------------------

    MeetPopup(SpriteBatch batch, ShapeRenderer sr,
              BitmapFont font, BitmapFont smallFont, GlyphLayout glyph) {
        this.batch     = batch;
        this.sr        = sr;
        this.font      = font;
        this.smallFont = smallFont;
        this.glyph     = glyph;
    }

    // -------------------------------------------------------------------------
    // State queries
    // -------------------------------------------------------------------------

    boolean isVisible() { return visible; }

    // -------------------------------------------------------------------------
    // Commands
    // -------------------------------------------------------------------------

    /**
     * Opens the meet popup for the given calendar entry.
     *
     * <p>Personality attributes (charisma, empathy, nervousness) are derived
     * deterministically from the contact name so that the same client always
     * produces the same introduction style, while still varying per client.
     *
     * @param entry      the upcoming appointment; must not be {@code null}
     * @param caseContext short objective string from the matching {@link CaseFile}
     *                   (may be empty or {@code null})
     */
    void show(CalendarEntry entry, String caseContext) {
        if (entry == null) return;

        contactName = entry.contactName.isEmpty() ? entry.title : entry.contactName;
        String gender = entry.contactGender;

        // Derive personality attributes from a stable hash of the contact name.
        int nameHash = Math.abs(contactName.hashCode());
        int charisma    = 1 + (nameHash % 10);
        int empathy     = 1 + ((nameHash / 10) % 10);
        int nervousness = 1 + ((nameHash / 100) % 10);

        introText  = ClientIntroductionGenerator.buildIntroduction(
                contactName, gender, charisma, empathy, nervousness, caseContext);
        replyText  = ClientIntroductionGenerator.buildDetectiveReply(contactName);
        questions  = new ArrayList<>(ClientIntroductionGenerator.buildQuestions());
        questionAsked = new boolean[questions.size()];

        qBtnX = new float[questions.size()];
        qBtnY = new float[questions.size()];
        qBtnW = new float[questions.size()];

        visible = true;
    }

    /** Hides the popup. */
    void hide() { visible = false; }

    // -------------------------------------------------------------------------
    // Input handling
    // -------------------------------------------------------------------------

    /**
     * Handles a tap on this popup.
     *
     * @param screenX  x coordinate (screen space, 0 = left)
     * @param flippedY y coordinate (OpenGL flipped: 0 = bottom)
     * @return index (≥ 0) of the tapped question, {@link #RESULT_CLOSED}, or
     *         {@link #RESULT_MISS}
     */
    int onTap(int screenX, int flippedY) {
        if (!visible) return RESULT_MISS;

        // Close button
        if (closeBtnW > 0
                && screenX >= closeBtnX && screenX <= closeBtnX + closeBtnW
                && flippedY >= closeBtnY && flippedY <= closeBtnY + closeBtnH) {
            visible = false;
            return RESULT_CLOSED;
        }

        // Question buttons
        if (qBtnW != null && qBtnH > 0) {
            for (int i = 0; i < questions.size(); i++) {
                if (qBtnW[i] <= 0) continue;
                if (screenX >= qBtnX[i] && screenX <= qBtnX[i] + qBtnW[i]
                        && flippedY >= qBtnY[i] && flippedY <= qBtnY[i] + qBtnH) {
                    questionAsked[i] = true;
                    return i;
                }
            }
        }

        return RESULT_MISS;
    }

    // -------------------------------------------------------------------------
    // Drawing
    // -------------------------------------------------------------------------

    /**
     * Draws the meet popup.
     * Does nothing when {@link #isVisible()} is {@code false}.
     *
     * @param screenW screen width in pixels
     * @param screenH screen height in pixels
     */
    void draw(int screenW, int screenH) {
        if (!visible) return;

        final float PAD      = 20f;
        final float GAP      = 8f;
        final float BTN_H_PX = 30f;
        final float CLOSE_H  = 28f;

        // Font metrics
        glyph.setText(font, "Hg");
        float fontH = glyph.height;
        glyph.setText(smallFont, "Hg");
        float smallH = glyph.height;

        // Dialog width
        float dW = Math.min(440f, screenW * 0.90f);
        float innerW = dW - PAD * 2f;
        dialogW = dW;

        // Measure wrapped text heights
        WordWrapper.WidthMeasurer measurer = t -> {
            glyph.setText(smallFont, t);
            return glyph.width;
        };
        List<String> introLines = WordWrapper.wrap(introText, innerW, measurer);
        List<String> replyLines = WordWrapper.wrap(replyText, innerW, measurer);

        float introH = introLines.size() * (smallH + GAP / 2f);
        float replyH = replyLines.size() * (smallH + GAP / 2f);

        int nQ = questions.size();
        qBtnH = BTN_H_PX;

        float questionsH = nQ > 0 ? nQ * (BTN_H_PX + GAP) : 0f;

        float dH = PAD
                + fontH + GAP          // title
                + GAP                  // spacer
                + smallH + GAP / 2f    // "Client:" label
                + introH + GAP         // intro text
                + 2f                   // divider
                + GAP
                + smallH + GAP / 2f    // "You:" label
                + replyH + GAP         // reply text
                + 2f                   // divider
                + GAP
                + questionsH           // question buttons
                + GAP
                + CLOSE_H              // close button
                + PAD;

        dH = MathUtils.clamp(dH, 240f, screenH * 0.92f);
        dialogH = dH;

        dialogX = (screenW - dW) / 2f;
        dialogY = (screenH - dH) / 2f;

        // ---- Background ----
        sr.begin(ShapeRenderer.ShapeType.Filled);
        sr.setColor(BG_COLOR);
        sr.rect(dialogX, dialogY, dW, dH);

        // Question button fills
        float curY = dialogY + PAD + CLOSE_H + GAP;
        for (int i = nQ - 1; i >= 0; i--) {
            curY += GAP;
            sr.setColor(questionAsked[i] ? BTN_FILL_ASKED : BTN_FILL);
            sr.rect(dialogX + PAD, curY, innerW, BTN_H_PX);
            qBtnX[i] = dialogX + PAD;
            qBtnY[i] = curY;
            qBtnW[i] = innerW;
            curY += BTN_H_PX;
        }

        // Close button fill
        closeBtnX = dialogX + PAD;
        closeBtnY = dialogY + PAD;
        closeBtnW = innerW;
        closeBtnH = CLOSE_H;
        sr.setColor(CLOSE_FILL);
        sr.rect(closeBtnX, closeBtnY, closeBtnW, closeBtnH);

        sr.end();

        // ---- Borders / dividers ----
        sr.begin(ShapeRenderer.ShapeType.Line);
        sr.setColor(BORDER_COLOR);
        sr.rect(dialogX,     dialogY,     dW,     dH);
        sr.rect(dialogX + 1, dialogY + 1, dW - 2, dH - 2);

        // Close button border
        sr.setColor(CLOSE_BORDER);
        sr.rect(closeBtnX, closeBtnY, closeBtnW, closeBtnH);

        // Question button borders
        for (int i = 0; i < nQ; i++) {
            if (qBtnW[i] > 0) {
                sr.setColor(BTN_BORDER);
                sr.rect(qBtnX[i], qBtnY[i], qBtnW[i], BTN_H_PX);
            }
        }

        // Divider line below reply block
        float divY1 = dialogY + PAD + CLOSE_H + GAP + questionsH + GAP;
        sr.setColor(DIVIDER_COLOR);
        sr.line(dialogX + PAD, divY1, dialogX + dW - PAD, divY1);

        // Divider line below intro block
        float divY2 = divY1 + GAP + smallH + GAP / 2f + replyH + GAP;
        sr.setColor(DIVIDER_COLOR);
        sr.line(dialogX + PAD, divY2, dialogX + dW - PAD, divY2);

        sr.end();

        // ---- Text ----
        batch.begin();

        // Title
        float titleY = dialogY + dH - PAD;
        String title = "Meeting: " + contactName;
        glyph.setText(font, title);
        font.setColor(TITLE_COLOR);
        font.draw(batch, title, dialogX + dW / 2f - glyph.width / 2f, titleY);

        // Close button label
        glyph.setText(smallFont, "Close");
        smallFont.setColor(CLOSE_TEXT);
        smallFont.draw(batch, "Close",
                closeBtnX + closeBtnW / 2f - glyph.width / 2f,
                closeBtnY + (closeBtnH + glyph.height) / 2f);

        // Question button labels
        for (int i = 0; i < nQ; i++) {
            if (qBtnW[i] <= 0) continue;
            String label = questions.get(i);
            String display = questionAsked[i] ? "✓ " + label : label;
            glyph.setText(smallFont, display);
            smallFont.setColor(questionAsked[i] ? BTN_ASKED_TEXT : BTN_TEXT);
            float tx = qBtnX[i] + 8f;
            float ty = qBtnY[i] + (BTN_H_PX + glyph.height) / 2f;
            smallFont.draw(batch, display, tx, ty);
        }

        // "Client:" label + intro text (drawn top-down from divY2 downward)
        float lineY = divY2 + GAP + smallH + GAP / 2f;
        smallFont.setColor(INTRO_LABEL_CLR);
        smallFont.draw(batch, contactName + ":", dialogX + PAD, lineY);
        for (String line : introLines) {
            lineY -= smallH + GAP / 2f;
            smallFont.setColor(INTRO_TEXT_CLR);
            smallFont.draw(batch, line, dialogX + PAD, lineY);
        }

        // "You:" label + reply text
        float replyStartY = divY1 + GAP + smallH + GAP / 2f;
        smallFont.setColor(REPLY_LABEL_CLR);
        smallFont.draw(batch, "You:", dialogX + PAD, replyStartY);
        float rLineY = replyStartY;
        for (String line : replyLines) {
            rLineY -= smallH + GAP / 2f;
            smallFont.setColor(REPLY_TEXT_CLR);
            smallFont.draw(batch, line, dialogX + PAD, rLineY);
        }

        batch.end();
    }
}
