package eb.framework1;

/**
 * An immutable question/answer pair used in the client-meeting dialogue.
 *
 * <p>Instances are generated by {@link CaseGenerator} as part of case generation
 * and stored on the {@link CaseFile} via {@link CaseFile#setMeetingDialogue}.
 * {@link MeetPopup} presents them as tappable question buttons; tapping a button
 * reveals the client's answer.
 *
 * <p>The dialogue set covers the base case context (objective, description,
 * timeline, contacts) plus one entry per
 * {@link CaseStoryNode.NodeType#PLOT_TWIST} phase so that all branches of the
 * story tree are represented.
 */
public final class MeetingQA {

    private final String question;
    private final String answer;

    /**
     * Creates a question/answer pair.
     *
     * @param question the question the detective asks; must not be {@code null}
     * @param answer   the client's reply; must not be {@code null}
     */
    public MeetingQA(String question, String answer) {
        this.question = question != null ? question : "";
        this.answer   = answer   != null ? answer   : "";
    }

    /** Returns the question text. */
    public String getQuestion() { return question; }

    /** Returns the client's answer text. */
    public String getAnswer()   { return answer; }
}
