package eb.framework1;

import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.GlyphLayout;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer;
import com.badlogic.gdx.math.MathUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * Modal popup shown when the player taps the "Meet [client]" button.
 *
 * <h3>Layout (top → bottom)</h3>
 * <ol>
 *   <li><strong>Title bar</strong> — "Meeting: [contactName]"</li>
 *   <li><strong>Client introduction</strong> — generated by
 *       {@link ClientIntroductionGenerator} using the client's gender and
 *       personality-influenced attributes.</li>
 *   <li><strong>Detective reply</strong> — a standard acknowledgement.</li>
 *   <li><strong>Question buttons</strong> — the player taps one to ask a
 *       follow-up question; the button is then marked "ASKED".</li>
 *   <li><strong>Close button</strong> — dismisses the popup.</li>
 * </ol>
 *
 * <h3>Usage (MainScreen)</h3>
 * <pre>
 *   meetPopup.show(entry);
 *   // each frame:
 *   meetPopup.draw(screenW, screenH);
 *   // on tap:
 *   int result = meetPopup.onTap(screenX, flippedY);
 *   // result >= 0  → question index tapped
 *   // RESULT_CLOSED → close button tapped
 *   // RESULT_MISS   → no interactive area hit
 * </pre>
 */
class MeetPopup {

    /** Returned by {@link #onTap} when the close button was tapped. */
    static final int RESULT_CLOSED = -1;
    /** Returned by {@link #onTap} when no interactive area was hit. */
    static final int RESULT_MISS   = -2;

    // ---- Colours ----
    private static final Color BG_COLOR        = new Color(0.05f, 0.08f, 0.14f, 1f);
    private static final Color BORDER_COLOR    = new Color(0.40f, 0.60f, 0.85f, 1f);
    private static final Color TITLE_COLOR     = new Color(0.80f, 0.90f, 1.00f, 1f);
    private static final Color DIVIDER_COLOR   = new Color(0.25f, 0.35f, 0.55f, 1f);
    private static final Color INTRO_LABEL_CLR = new Color(0.65f, 0.80f, 1.00f, 1f);
    private static final Color INTRO_TEXT_CLR  = new Color(0.88f, 0.88f, 0.88f, 1f);
    private static final Color REPLY_LABEL_CLR = new Color(0.50f, 1.00f, 0.65f, 1f);
    private static final Color REPLY_TEXT_CLR  = new Color(0.80f, 0.95f, 0.80f, 1f);
    private static final Color BTN_FILL        = new Color(0.12f, 0.25f, 0.42f, 1f);
    private static final Color BTN_FILL_ASKED  = new Color(0.10f, 0.30f, 0.15f, 1f);
    private static final Color BTN_BORDER      = new Color(0.35f, 0.55f, 0.80f, 1f);
    private static final Color BTN_TEXT        = new Color(0.90f, 0.90f, 0.90f, 1f);
    private static final Color BTN_ASKED_TEXT  = new Color(0.50f, 0.90f, 0.55f, 1f);
    private static final Color CLOSE_FILL      = new Color(0.40f, 0.10f, 0.10f, 1f);
    private static final Color CLOSE_BORDER    = new Color(0.75f, 0.28f, 0.28f, 1f);
    private static final Color CLOSE_TEXT      = new Color(0.95f, 0.90f, 0.90f, 1f);

    // ---- Rendering resources ----
    private final SpriteBatch   batch;
    private final ShapeRenderer sr;
    private final BitmapFont    font;
    private final BitmapFont    smallFont;
    private final GlyphLayout   glyph;

    // ---- Popup state ----
    private boolean      visible      = false;
    private String       contactName  = "";
    private String       introText    = "";
    private String       replyText    = "";
    private List<String> questions    = new ArrayList<>();
    private boolean[]    questionAsked;

    // ---- Hit-test bounds (written each frame during draw, read by onTap) ----
    private float dialogX, dialogY, dialogW, dialogH;
    private float closeBtnX, closeBtnY, closeBtnW, closeBtnH;
    private float[] qBtnX, qBtnY, qBtnW;
    private float   qBtnH;

    // (no instance state needed for word-wrap — WordWrapper is static)

    // -------------------------------------------------------------------------

    MeetPopup(SpriteBatch batch, ShapeRenderer sr,
              BitmapFont font, BitmapFont smallFont, GlyphLayout glyph) {
        this.batch     = batch;
        this.sr        = sr;
        this.font      = font;
        this.smallFont = smallFont;
        this.glyph     = glyph;
    }

    // -------------------------------------------------------------------------
    // State queries
    // -------------------------------------------------------------------------

    boolean isVisible() { return visible; }

    // -------------------------------------------------------------------------
    // Commands
    // -------------------------------------------------------------------------

    /**
     * Opens the meet popup for the given calendar entry.
     *
     * <p>Personality attributes (charisma, empathy, nervousness) are derived
     * deterministically from the contact name so that the same client always
     * produces the same introduction style, while still varying per client.
     *
     * @param entry      the upcoming appointment; must not be {@code null}
     * @param caseContext short objective string from the matching {@link CaseFile}
     *                   (may be empty or {@code null})
     */
    void show(CalendarEntry entry, String caseContext) {
        if (entry == null) return;

        contactName = entry.contactName.isEmpty() ? entry.title : entry.contactName;
        String gender = entry.contactGender;

        // Derive personality attributes from a stable hash of the contact name.
        int nameHash = Math.abs(contactName.hashCode());
        int charisma    = 1 + (nameHash % 10);
        int empathy     = 1 + ((nameHash / 10) % 10);
        int nervousness = 1 + ((nameHash / 100) % 10);

        introText  = ClientIntroductionGenerator.buildIntroduction(
                contactName, gender, charisma, empathy, nervousness, caseContext);
        replyText  = ClientIntroductionGenerator.buildDetectiveReply(contactName);
        questions  = new ArrayList<>(ClientIntroductionGenerator.buildQuestions());
        questionAsked = new boolean[questions.size()];

        qBtnX = new float[questions.size()];
        qBtnY = new float[questions.size()];
        qBtnW = new float[questions.size()];

        visible = true;
    }

    /** Hides the popup. */
    void hide() { visible = false; }

    // -------------------------------------------------------------------------
    // Input handling
    // -------------------------------------------------------------------------

    /**
     * Handles a tap on this popup.
     *
     * @param screenX  x coordinate (screen space, 0 = left)
     * @param flippedY y coordinate (OpenGL flipped: 0 = bottom)
     * @return index (≥ 0) of the tapped question, {@link #RESULT_CLOSED}, or
     *         {@link #RESULT_MISS}
     */
    int onTap(int screenX, int flippedY) {
        if (!visible) return RESULT_MISS;

        // Close button
        if (closeBtnW > 0
                && screenX >= closeBtnX && screenX <= closeBtnX + closeBtnW
                && flippedY >= closeBtnY && flippedY <= closeBtnY + closeBtnH) {
            visible = false;
            return RESULT_CLOSED;
        }

        // Question buttons
        if (qBtnW != null && qBtnH > 0) {
            for (int i = 0; i < questions.size(); i++) {
                if (qBtnW[i] <= 0) continue;
                if (screenX >= qBtnX[i] && screenX <= qBtnX[i] + qBtnW[i]
                        && flippedY >= qBtnY[i] && flippedY <= qBtnY[i] + qBtnH) {
                    questionAsked[i] = true;
                    return i;
                }
            }
        }

        return RESULT_MISS;
    }

    // -------------------------------------------------------------------------
    // Drawing
    // -------------------------------------------------------------------------

    /**
     * Draws the meet popup spanning the full screen width.
     * Does nothing when {@link #isVisible()} is {@code false}.
     *
     * <p>Layout (top → bottom, each element placed with a single top-down
     * {@code curY} tracker so spacing is consistent and easy to audit):
     * <pre>
     *   PAD
     *   title (font)
     *   SECTION_GAP + title-divider + SECTION_GAP
     *   "Client:" label (smallFont, coloured)
     *   introLines × lineH
     *   SECTION_GAP + divider + SECTION_GAP
     *   "You:" label (smallFont, coloured)
     *   replyLines × lineH
     *   SECTION_GAP + divider + SECTION_GAP
     *   nQ × (BTN_H + BTN_GAP)   question buttons
     *   SECTION_GAP
     *   CLOSE_H                   close button
     *   PAD
     * </pre>
     *
     * @param screenW screen width in pixels
     * @param screenH screen height in pixels
     */
    void draw(int screenW, int screenH) {
        if (!visible) return;

        // ---- Layout constants ----
        final float PAD         = 16f;  // inner horizontal padding and top/bottom pad
        final float LINE_GAP    = 4f;   // vertical gap between consecutive text lines
        final float SECTION_GAP = 12f;  // vertical gap between major content sections
        final float DIVIDER_H   = 1f;   // height of section-divider line
        final float BTN_H       = 32f;  // question button height
        final float BTN_GAP     = 6f;   // gap between consecutive question buttons
        final float CLOSE_H     = 32f;  // close button height

        // ---- Font metrics ----
        glyph.setText(font, "Hg");
        float fontH  = glyph.height;
        glyph.setText(smallFont, "Hg");
        float smallH = glyph.height;
        float lineH  = smallH + LINE_GAP;

        // ---- Full-width dialog ----
        float dW    = screenW;
        float innerW = dW - PAD * 2f;
        dialogW = dW;
        dialogX = 0f;

        // ---- Word-wrap both text blocks to the inner width ----
        WordWrapper.WidthMeasurer msr = t -> {
            glyph.setText(smallFont, t);
            return glyph.width;
        };
        List<String> introLines = WordWrapper.wrap(introText, innerW, msr);
        List<String> replyLines = WordWrapper.wrap(replyText, innerW, msr);

        int nQ = questions.size();
        qBtnH = BTN_H;

        // ---- Compute required dialog height from the layout formula ----
        // Each term corresponds to exactly one visual element in order.
        float dH = PAD                                          // top pad
                + fontH + SECTION_GAP                          // title text + gap below
                + DIVIDER_H + SECTION_GAP                      // title divider + gap below
                + lineH                                        // "Client:" label
                + introLines.size() * lineH                    // intro text lines
                + SECTION_GAP                                  // gap before intro divider
                + DIVIDER_H + SECTION_GAP                      // intro/reply divider + gap below
                + lineH                                        // "You:" label
                + replyLines.size() * lineH                    // reply text lines
                + SECTION_GAP                                  // gap before reply divider
                + DIVIDER_H + SECTION_GAP                      // reply/questions divider + gap below
                + nQ * (BTN_H + BTN_GAP)                       // question buttons (incl. gap after last)
                + SECTION_GAP                                  // gap between questions and close
                + CLOSE_H                                      // close button
                + PAD;                                         // bottom pad

        // Never taller than the screen; never shorter than 240px or half the screen height.
        dH = MathUtils.clamp(dH, Math.max(240f, screenH * 0.50f), (float) screenH);
        dialogH = dH;
        dialogY = (screenH - dH) / 2f;

        // ---- Top-down position tracking ----
        // 'curY' is the Y of the TOP of the next element to be placed.
        // In libGDX Y=0 is at the screen bottom, so curY decreases as we move
        // visually downward.  For text: font.draw(batch, text, x, curY) places
        // the text top at curY; the glyph extends downward to curY-smallH.
        // For button rects: qBtnY[i] = curY - BTN_H (the rect's bottom edge).
        float curY = dialogY + dH - PAD;

        // Title
        float titleY = curY;
        curY -= fontH + SECTION_GAP;

        // Title divider
        float titleDivY = curY;
        curY -= DIVIDER_H + SECTION_GAP;

        // "Client:" label
        float introLabelY = curY;
        curY -= lineH;

        // Intro text lines
        float[] introLineY = new float[introLines.size()];
        for (int i = 0; i < introLines.size(); i++) {
            introLineY[i] = curY;
            curY -= lineH;
        }
        curY -= SECTION_GAP;

        // Intro / reply divider
        float introDivY = curY;
        curY -= DIVIDER_H + SECTION_GAP;

        // "You:" label
        float replyLabelY = curY;
        curY -= lineH;

        // Reply text lines
        float[] replyLineY = new float[replyLines.size()];
        for (int i = 0; i < replyLines.size(); i++) {
            replyLineY[i] = curY;
            curY -= lineH;
        }
        curY -= SECTION_GAP;

        // Reply / questions divider
        float replyDivY = curY;
        curY -= DIVIDER_H + SECTION_GAP;

        // Question buttons (rect bottom = curY - BTN_H)
        for (int i = 0; i < nQ; i++) {
            qBtnY[i] = curY - BTN_H;
            qBtnX[i] = dialogX + PAD;
            qBtnW[i] = innerW;
            curY -= BTN_H + BTN_GAP;
        }
        curY -= SECTION_GAP;

        // Close button (rect bottom = curY - CLOSE_H)
        closeBtnY = curY - CLOSE_H;
        closeBtnX = dialogX + PAD;
        closeBtnW = innerW;
        closeBtnH = CLOSE_H;

        // ---- Shapes: filled ----
        sr.begin(ShapeRenderer.ShapeType.Filled);

        sr.setColor(BG_COLOR);
        sr.rect(dialogX, dialogY, dW, dH);

        for (int i = 0; i < nQ; i++) {
            sr.setColor(questionAsked[i] ? BTN_FILL_ASKED : BTN_FILL);
            sr.rect(qBtnX[i], qBtnY[i], innerW, BTN_H);
        }

        sr.setColor(CLOSE_FILL);
        sr.rect(closeBtnX, closeBtnY, closeBtnW, closeBtnH);

        sr.end();

        // ---- Shapes: borders and dividers ----
        sr.begin(ShapeRenderer.ShapeType.Line);

        sr.setColor(BORDER_COLOR);
        sr.rect(dialogX,     dialogY,     dW,     dH);
        sr.rect(dialogX + 1, dialogY + 1, dW - 2, dH - 2);

        sr.setColor(DIVIDER_COLOR);
        sr.line(dialogX + PAD, titleDivY, dialogX + dW - PAD, titleDivY);
        sr.line(dialogX + PAD, introDivY, dialogX + dW - PAD, introDivY);
        sr.line(dialogX + PAD, replyDivY, dialogX + dW - PAD, replyDivY);

        sr.setColor(CLOSE_BORDER);
        sr.rect(closeBtnX, closeBtnY, closeBtnW, closeBtnH);

        for (int i = 0; i < nQ; i++) {
            if (qBtnW[i] > 0) {
                sr.setColor(BTN_BORDER);
                sr.rect(qBtnX[i], qBtnY[i], qBtnW[i], BTN_H);
            }
        }

        sr.end();

        // ---- Text ----
        batch.begin();

        // Title — centred horizontally
        String titleStr = "Meeting: " + contactName;
        glyph.setText(font, titleStr);
        font.setColor(TITLE_COLOR);
        font.draw(batch, titleStr, dialogX + dW / 2f - glyph.width / 2f, titleY);

        // "Client:" label
        smallFont.setColor(INTRO_LABEL_CLR);
        smallFont.draw(batch, contactName + ":", dialogX + PAD, introLabelY);

        // Intro text lines
        smallFont.setColor(INTRO_TEXT_CLR);
        for (int i = 0; i < introLines.size(); i++) {
            smallFont.draw(batch, introLines.get(i), dialogX + PAD, introLineY[i]);
        }

        // "You:" label
        smallFont.setColor(REPLY_LABEL_CLR);
        smallFont.draw(batch, "You:", dialogX + PAD, replyLabelY);

        // Reply text lines
        smallFont.setColor(REPLY_TEXT_CLR);
        for (int i = 0; i < replyLines.size(); i++) {
            smallFont.draw(batch, replyLines.get(i), dialogX + PAD, replyLineY[i]);
        }

        // Question button labels — vertically centred inside each button
        for (int i = 0; i < nQ; i++) {
            if (qBtnW[i] <= 0) continue;
            String label   = questions.get(i);
            String display = questionAsked[i] ? "\u2713 " + label : label;
            glyph.setText(smallFont, display);
            smallFont.setColor(questionAsked[i] ? BTN_ASKED_TEXT : BTN_TEXT);
            float ty = qBtnY[i] + (BTN_H + glyph.height) / 2f;
            smallFont.draw(batch, display, qBtnX[i] + 8f, ty);
        }

        // Close button label — centred
        glyph.setText(smallFont, "Close");
        smallFont.setColor(CLOSE_TEXT);
        smallFont.draw(batch, "Close",
                closeBtnX + closeBtnW / 2f - glyph.width / 2f,
                closeBtnY + (closeBtnH + glyph.height) / 2f);

        batch.end();
    }
}
