package eb.framework1.investigation;

import eb.framework1.character.PersonalityTrait;
import eb.framework1.phone.*;


import java.util.ArrayList;
import java.util.Collections;
import java.util.EnumMap;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Represents a case file in the game.  Each case tracks clues and evidence
 * gathered by the player during an investigation.  Multiple cases may be open
 * at the same time.
 *
 * <p>Cases generated by {@link CaseGenerator} carry additional context fields:
 * the {@link CaseType}, the client who hired the detective, the subject of the
 * investigation, a clear objective statement, a list of {@link CaseLead}s —
 * hidden facts the player must uncover to solve the case — a
 * <em>complexity</em> level (1–3, hidden from the player) that controls how
 * many plot twists the investigation contains (1 = none, 2 = one, 3 = two),
 * and a {@link CaseStoryNode} <em>story tree</em> that maps every step of the
 * investigation as a four-level hierarchy (plot-twist phases → major milestones
 * → minor tasks → leaf actions), and a pre-generated meeting dialogue — a list
 * of {@link MeetingQA} pairs (one question + answer per story-tree branch) that
 * the client delivers during the initial appointment.
 */
public class CaseFile {

    /** Possible statuses for a case. */
    public enum Status {
        OPEN, CLOSED, COLD
    }

    private final String id;
    private String name;
    private String description;
    private Status status;
    private String dateOpened;
    private String dateClosed;
    private final List<String>       clues;
    private final List<String>       evidence;
    private final List<String>       notes;
    private final List<EvidenceItem> evidenceItems;
    private final List<KnownFact>    knownFacts;

    // ---- Fields populated by CaseGenerator ----
    /** Broad category of the case (nullable for legacy/manual cases). */
    private CaseType caseType;
    /** Name of the client who hired the detective. */
    private String clientName;
    /** Name of the person or entity being investigated. */
    private String subjectName;
    /** Name of the victim (separate person in Murder cases; empty otherwise). */
    private String victimName;
    /**
     * One-sentence statement of what the player must find out or prove to
     * resolve the case (the client's ask).
     */
    private String objective;
    /** Hidden facts the player must uncover. */
    private final List<CaseLead> leads;
    /**
     * Hidden complexity of the case (not shown to the player).
     * <ul>
     *   <li>1 — straightforward, no plot twists</li>
     *   <li>2 — one plot twist during the investigation</li>
     *   <li>3 — two plot twists during the investigation</li>
     * </ul>
     */
    private int complexity;
    /**
     * Root of the story-progression tree.  {@code null} for legacy / manually
     * created cases.  Populated by {@link CaseGenerator}.
     */
    private CaseStoryNode storyRoot;

    /**
     * Pre-generated meeting dialogue: one {@link MeetingQA} entry per question
     * the client is prepared to answer during the initial appointment.
     * Generated by {@link CaseGenerator}; empty for legacy / manual cases.
     */
    private List<MeetingQA> meetingDialogue;

    /**
     * Pre-generated interview scripts: one {@link InterviewScript} per NPC
     * who can be interviewed (alive, case-relevant characters).  Each script
     * contains responses covering alibis, opinions of other characters,
     * whereabouts at the time of the crime, and other investigative topics.
     * Generated by {@link CaseGenerator}; empty for legacy / manual cases.
     */
    private final List<InterviewScript> interviewScripts;

    /**
     * Hidden personality traits for each NPC in the case, keyed by NPC name.
     * Each value is a map of {@link PersonalityTrait} → integer (−3 to +3).
     * Generated by {@link CaseGenerator}; empty for legacy / manual cases.
     *
     * <p>These traits are not shown to the player until discovered through
     * interviews, but are used by the story generator to derive motives,
     * plausible locations, and behavioural patterns.
     */
    private final Map<String, Map<PersonalityTrait, Integer>> npcPersonalityTraits;

    /**
     * Creates a new open case file with a generated id and no clues or evidence.
     *
     * @param name        short name of the case (shown in the poplist)
     * @param description longer summary of the case
     * @param dateOpened  in-game date/time when the case was opened
     */
    public CaseFile(String name, String description, String dateOpened) {
        this(UUID.randomUUID().toString(), name, description, Status.OPEN, dateOpened, null,
                new ArrayList<>(), new ArrayList<>(), new ArrayList<>(), new ArrayList<>());
    }

    /**
     * Full constructor — used mainly when restoring a case from a save file.
     */
    public CaseFile(String id, String name, String description, Status status,
                    String dateOpened, String dateClosed, List<String> clues,
                    List<String> evidence, List<String> notes) {
        this(id, name, description, status, dateOpened, dateClosed, clues, evidence, notes,
                new ArrayList<>());
    }

    /**
     * Full constructor including physical evidence items — used mainly when
     * restoring a case from a save file.
     */
    public CaseFile(String id, String name, String description, Status status,
                    String dateOpened, String dateClosed, List<String> clues,
                    List<String> evidence, List<String> notes,
                    List<EvidenceItem> evidenceItems) {
        if (name == null || name.trim().isEmpty()) {
            throw new IllegalArgumentException("Case name cannot be null or empty");
        }
        this.id          = id != null ? id : UUID.randomUUID().toString();
        this.name        = name;
        this.description = description != null ? description : "";
        this.status      = status != null ? status : Status.OPEN;
        this.dateOpened   = dateOpened != null ? dateOpened : "";
        this.dateClosed   = dateClosed;
        this.clues         = clues != null ? new ArrayList<>(clues) : new ArrayList<>();
        this.evidence      = evidence != null ? new ArrayList<>(evidence) : new ArrayList<>();
        this.notes         = notes != null ? new ArrayList<>(notes) : new ArrayList<>();
        this.evidenceItems = evidenceItems != null ? new ArrayList<>(evidenceItems) : new ArrayList<>();
        this.knownFacts    = new ArrayList<>();
        // Generator-populated fields default to empty/null
        this.caseType    = null;
        this.clientName  = "";
        this.subjectName = "";
        this.victimName  = "";
        this.objective   = "";
        this.leads       = new ArrayList<>();
        this.complexity  = 1;
        this.storyRoot   = null;
        this.meetingDialogue = new ArrayList<>();
        this.interviewScripts = new ArrayList<>();
        this.npcPersonalityTraits = new HashMap<>();
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public String getId()          { return id; }
    public String getName()        { return name; }
    public String getDescription() { return description; }
    public Status getStatus()      { return status; }
    public String getDateOpened()  { return dateOpened; }
    public String getDateClosed()  { return dateClosed; }

    public void setName(String name)               { this.name = name; }
    public void setDescription(String description) { this.description = description; }
    public void setDateOpened(String dateOpened)    { this.dateOpened = dateOpened; }

    // ---- Generator-populated fields ----

    /** Returns the broad category of this case, or {@code null} for legacy/manual cases. */
    public CaseType getCaseType() { return caseType; }
    /** Sets the case category (called by {@link CaseGenerator}). */
    public void setCaseType(CaseType caseType) { this.caseType = caseType; }

    /** Name of the client who hired the detective (empty string if not set). */
    public String getClientName() { return clientName; }
    /** Sets the client name. */
    public void setClientName(String clientName) {
        this.clientName = clientName != null ? clientName : "";
    }

    /** Name of the person or entity being investigated (empty string if not set). */
    public String getSubjectName() { return subjectName; }
    /** Sets the subject name. */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName != null ? subjectName : "";
    }

    /** Name of the victim (empty string if not applicable). */
    public String getVictimName() { return victimName; }
    /** Sets the victim name. */
    public void setVictimName(String victimName) {
        this.victimName = victimName != null ? victimName : "";
    }

    /**
     * One-sentence statement of what the player must find out or prove to
     * resolve the case (the client's ask).  Empty string if not set.
     */
    public String getObjective() { return objective; }
    /** Sets the case objective. */
    public void setObjective(String objective) {
        this.objective = objective != null ? objective : "";
    }

    /**
     * Returns the hidden complexity of the case (1–3).
     * <ul>
     *   <li>1 — straightforward, no plot twists</li>
     *   <li>2 — one plot twist during the investigation</li>
     *   <li>3 — two plot twists during the investigation</li>
     * </ul>
     * This value is not shown to the player.
     */
    public int getComplexity() { return complexity; }

    /**
     * Sets the hidden complexity of the case.
     *
     * @param complexity must be 1, 2, or 3
     * @throws IllegalArgumentException if the value is outside the 1–3 range
     */
    public void setComplexity(int complexity) {
        if (complexity < 1 || complexity > 3) {
            throw new IllegalArgumentException("complexity must be 1, 2, or 3 but was " + complexity);
        }
        this.complexity = complexity;
    }

    /**
     * Returns the root of the story-progression tree, or {@code null} for
     * legacy / manually created cases that have no generated story tree.
     *
     * <p>The root node has type {@link CaseStoryNode.NodeType#ROOT}; its
     * children are the {@link CaseStoryNode.NodeType#PLOT_TWIST} phase nodes.
     */
    public CaseStoryNode getStoryRoot() { return storyRoot; }

    /**
     * Sets the story-progression tree root.  Called by {@link CaseGenerator};
     * pass {@code null} to clear the tree.
     */
    public void setStoryRoot(CaseStoryNode storyRoot) { this.storyRoot = storyRoot; }

    /**
     * Returns an unmodifiable view of the pre-generated meeting dialogue.
     * Each entry is a question/answer pair covering a branch of the story tree.
     * Returns an empty list for legacy / manually created cases.
     */
    public List<MeetingQA> getMeetingDialogue() {
        return Collections.unmodifiableList(meetingDialogue);
    }

    /**
     * Replaces the meeting dialogue.  Called by {@link CaseGenerator} after
     * the story tree is built.  Passing {@code null} or an empty list clears
     * the dialogue.
     */
    public void setMeetingDialogue(List<MeetingQA> dialogue) {
        this.meetingDialogue.clear();
        if (dialogue != null) {
            this.meetingDialogue.addAll(dialogue);
        }
    }

    /**
     * Returns an unmodifiable view of the pre-generated interview scripts.
     * Each entry is an {@link InterviewScript} for one NPC, containing
     * responses about alibis, opinions, whereabouts, and other topics.
     * Returns an empty list for legacy / manually created cases.
     */
    public List<InterviewScript> getInterviewScripts() {
        return Collections.unmodifiableList(interviewScripts);
    }

    /**
     * Returns the interview script for the NPC with the given name, or
     * {@code null} if no script exists for that character.
     *
     * @param npcName the display name of the NPC
     */
    public InterviewScript getInterviewScript(String npcName) {
        if (npcName == null) return null;
        for (InterviewScript script : interviewScripts) {
            if (npcName.equals(script.getNpcName())) return script;
        }
        return null;
    }

    /**
     * Replaces all interview scripts.  Called by {@link CaseGenerator} after
     * NPCs are generated.  Passing {@code null} or an empty list clears the
     * scripts.
     */
    public void setInterviewScripts(List<InterviewScript> scripts) {
        this.interviewScripts.clear();
        if (scripts != null) {
            this.interviewScripts.addAll(scripts);
        }
    }

    /**
     * Adds a single interview script to this case.
     *
     * @param script must not be {@code null}
     * @throws IllegalArgumentException if {@code script} is {@code null}
     */
    public void addInterviewScript(InterviewScript script) {
        if (script == null) {
            throw new IllegalArgumentException("InterviewScript must not be null");
        }
        interviewScripts.add(script);
    }

    // ---- NPC personality traits ----

    /**
     * Returns an unmodifiable view of the hidden personality traits for the
     * specified NPC, or an empty map if no traits have been assigned.
     *
     * @param npcName the display name of the NPC
     * @return trait map (never {@code null})
     */
    public Map<PersonalityTrait, Integer> getNpcTraits(String npcName) {
        Map<PersonalityTrait, Integer> traits = npcPersonalityTraits.get(npcName);
        return traits != null ? Collections.unmodifiableMap(traits) : Collections.emptyMap();
    }

    /**
     * Returns an unmodifiable view of all NPC personality-trait maps.
     * Outer key is the NPC name; inner map is trait → value (−3 to +3).
     */
    public Map<String, Map<PersonalityTrait, Integer>> getAllNpcTraits() {
        return Collections.unmodifiableMap(npcPersonalityTraits);
    }

    /**
     * Stores personality traits for the given NPC.  Overwrites any previous
     * entry for that NPC name.
     *
     * @param npcName the NPC's display name
     * @param traits  trait values; {@code null} removes the entry
     */
    public void setNpcTraits(String npcName, Map<PersonalityTrait, Integer> traits) {
        if (npcName == null) return;
        if (traits == null || traits.isEmpty()) {
            npcPersonalityTraits.remove(npcName);
        } else {
            npcPersonalityTraits.put(npcName, new EnumMap<>(traits));
        }
    }

    /** Returns an unmodifiable view of the clues recorded against this case. */
    public List<String> getClues() {
        return Collections.unmodifiableList(clues);
    }

    /** Returns an unmodifiable view of the evidence recorded against this case. */
    public List<String> getEvidence() {
        return Collections.unmodifiableList(evidence);
    }

    /** Returns an unmodifiable view of the player notes recorded against this case. */
    public List<String> getNotes() {
        return Collections.unmodifiableList(notes);
    }

    /**
     * Returns an unmodifiable view of the physical {@link EvidenceItem}s
     * collected for this case.
     */
    public List<EvidenceItem> getEvidenceItems() {
        return Collections.unmodifiableList(evidenceItems);
    }

    /**
     * Returns an unmodifiable list of physical evidence items that have at
     * least one analysis submitted.
     */
    public List<EvidenceItem> getSubmittedEvidenceItems() {
        return evidenceItems.stream()
                .filter(item -> !item.getSubmittedModifiers().isEmpty())
                .collect(Collectors.toList());
    }

    /**
     * Returns an unmodifiable view of all {@link KnownFact}s recorded against
     * this case, regardless of source.
     */
    public List<KnownFact> getKnownFacts() {
        return Collections.unmodifiableList(knownFacts);
    }

    /**
     * Returns an unmodifiable list of known facts that originated from the
     * given {@link FactSource}.
     *
     * @param source the source to filter by; must not be {@code null}
     */
    public List<KnownFact> getKnownFactsBySource(FactSource source) {
        if (source == null) {
            throw new IllegalArgumentException("FactSource must not be null");
        }
        return knownFacts.stream()
                .filter(f -> f.getSource() == source)
                .collect(Collectors.toList());
    }

    /**
     * Returns an unmodifiable view of the hidden {@link CaseLead}s attached to
     * this case.
     */
    public List<CaseLead> getLeads() {
        return Collections.unmodifiableList(leads);
    }

    /**
     * Returns an unmodifiable list of leads that the player has already
     * uncovered (i.e. {@link CaseLead#isDiscovered()} is {@code true}).
     */
    public List<CaseLead> getDiscoveredLeads() {
        return leads.stream()
                .filter(CaseLead::isDiscovered)
                .collect(Collectors.toList());
    }

    /**
     * Returns an unmodifiable list of leads that the player has not yet
     * uncovered.
     */
    public List<CaseLead> getUndiscoveredLeads() {
        return leads.stream()
                .filter(l -> !l.isDiscovered())
                .collect(Collectors.toList());
    }

    // -------------------------------------------------------------------------
    // Mutation helpers
    // -------------------------------------------------------------------------

    /** Adds a clue to this case. */
    public void addClue(String clue) {
        if (clue != null && !clue.trim().isEmpty()) {
            clues.add(clue);
        }
    }

    /** Adds a piece of evidence to this case. */
    public void addEvidence(String item) {
        if (item != null && !item.trim().isEmpty()) {
            evidence.add(item);
        }
    }

    /**
     * Adds a physical {@link EvidenceItem} to this case.
     *
     * @param item the item to add; must not be {@code null}
     * @throws IllegalArgumentException if {@code item} is {@code null}
     */
    public void addEvidenceItem(EvidenceItem item) {
        if (item == null) {
            throw new IllegalArgumentException("Evidence item must not be null");
        }
        evidenceItems.add(item);
    }

    /**
     * Records a {@link KnownFact} against this case.  The fact's
     * {@link FactSource} tracks how it was obtained (CASE, POLICE, or
     * DISCOVERED).
     *
     * @param fact the known fact to record; must not be {@code null}
     * @throws IllegalArgumentException if {@code fact} is {@code null}
     */
    public void addKnownFact(KnownFact fact) {
        if (fact == null) {
            throw new IllegalArgumentException("KnownFact must not be null");
        }
        knownFacts.add(fact);
    }

    /**
     * Convenience method: creates a {@link KnownFact} with the given text and
     * source, then records it on this case.
     *
     * @param text   fact description; must not be blank
     * @param source how the fact was obtained; must not be null
     */
    public void addKnownFact(String text, FactSource source) {
        addKnownFact(new KnownFact(text, source));
    }

    /**
     * Attaches a hidden {@link CaseLead} to this case.
     *
     * @param lead the lead to add; must not be {@code null}
     * @throws IllegalArgumentException if {@code lead} is {@code null}
     */
    public void addLead(CaseLead lead) {
        if (lead == null) {
            throw new IllegalArgumentException("CaseLead must not be null");
        }
        leads.add(lead);
    }

    /** Adds a player note to this case. */
    public void addNote(String note) {
        if (note != null && !note.trim().isEmpty()) {
            notes.add(note);
        }
    }

    /** Closes the case and records the closing date. */
    public void close(String dateClosed) {
        this.status = Status.CLOSED;
        this.dateClosed = dateClosed;
    }

    /** Marks the case as cold (inactive but not solved). */
    public void markCold() {
        this.status = Status.COLD;
    }

    /** Re-opens a closed or cold case. */
    public void reopen() {
        this.status = Status.OPEN;
        this.dateClosed = null;
    }

    /** Returns true when the case status is {@link Status#OPEN}. */
    public boolean isOpen() {
        return status == Status.OPEN;
    }

    @Override
    public String toString() {
        return "CaseFile{name='" + name + "', status=" + status + ", clues=" + clues.size() + ", evidence=" + evidence.size() + ", notes=" + notes.size() + "}";
    }
}
