package eb.framework1.investigation;

/**
 * An immutable question/answer pair from an NPC interview, together with
 * metadata about truthfulness and the character being discussed.
 *
 * <p>Instances are generated by {@link CaseGenerator} (or the admin-tool
 * equivalent) and stored on an {@link InterviewScript}.  The player sees the
 * {@link #getQuestion() question} and {@link #getAnswer() answer} text; the
 * {@link #isTruthful()} flag is hidden from the player and used by game
 * systems to control lead discovery and alibi verification.
 *
 * <p>The {@link #getAboutNpcName()} field is non-empty when the question
 * concerns a specific other character (e.g. "What do you think of Alice?").
 * For self-referencing topics like {@link InterviewTopic#ALIBI} the field is
 * empty.
 */
public final class InterviewResponse {

    private final InterviewTopic topic;
    private final String question;
    private final String answer;
    private final boolean truthful;
    private final String aboutNpcName;

    /**
     * Creates an interview response.
     *
     * @param topic        the category of this exchange; must not be {@code null}
     * @param question     the detective's question text; must not be {@code null}
     * @param answer       the NPC's reply; must not be {@code null}
     * @param truthful     {@code true} if the answer is factually accurate
     * @param aboutNpcName the name of the NPC the question is about, or empty
     *                     if the question is self-referencing
     */
    public InterviewResponse(InterviewTopic topic, String question, String answer,
                             boolean truthful, String aboutNpcName) {
        this.topic        = topic   != null ? topic   : InterviewTopic.OBSERVATION;
        this.question     = question != null ? question : "";
        this.answer       = answer   != null ? answer   : "";
        this.truthful     = truthful;
        this.aboutNpcName = aboutNpcName != null ? aboutNpcName : "";
    }

    /** Returns the interview topic. */
    public InterviewTopic getTopic() { return topic; }

    /** Returns the detective's question text. */
    public String getQuestion() { return question; }

    /** Returns the NPC's answer text. */
    public String getAnswer() { return answer; }

    /**
     * Returns {@code true} if the NPC's answer is factually accurate.
     *
     * <p>This flag is <em>hidden from the player</em> — it controls whether
     * game systems should treat the answer as reliable when checking alibis,
     * verifying leads, and awarding discovery points.
     */
    public boolean isTruthful() { return truthful; }

    /**
     * Returns the name of the character this question is about, or an empty
     * string if the question is self-referencing (e.g. an alibi question
     * about the interviewee themselves).
     */
    public String getAboutNpcName() { return aboutNpcName; }

    @Override
    public String toString() {
        return "InterviewResponse{topic=" + topic
                + ", aboutNpc='" + aboutNpcName + "'"
                + ", truthful=" + truthful + '}';
    }
}
