package eb.framework1.investigation;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

/**
 * The complete set of interview responses for one NPC in a case.
 *
 * <p>Each NPC who can be interviewed (i.e. is alive and part of the case)
 * has exactly one {@code InterviewScript} containing pre-generated
 * {@link InterviewResponse} entries covering multiple
 * {@link InterviewTopic}s.
 *
 * <p>The responses are generated by {@link CaseGenerator} based on the
 * NPC's role, personality traits (cooperativeness, honesty, nervousness),
 * and their relationships with other characters in the case.
 *
 * <h3>Example</h3>
 * <pre>
 *   InterviewScript script = new InterviewScript("npc-3", "Helen Davis", "Key Witness");
 *   script.addResponse(new InterviewResponse(
 *       InterviewTopic.ALIBI,
 *       "Where were you on the night of the incident?",
 *       "I was at home all evening. My neighbour can confirm.",
 *       true, ""));
 *   script.addResponse(new InterviewResponse(
 *       InterviewTopic.OPINION,
 *       "What do you think of Robert Smith?",
 *       "He's always been jealous of the victim's success.",
 *       true, "Robert Smith"));
 * </pre>
 */
public final class InterviewScript {

    private final String npcId;
    private final String npcName;
    private final String npcRole;
    private final List<InterviewResponse> responses;

    /**
     * Creates an empty interview script for the given NPC.
     *
     * @param npcId   unique identifier for this NPC within the case
     * @param npcName display name of the NPC being interviewed
     * @param npcRole the NPC's role in the case (e.g. "Key Witness",
     *                "Subject (Suspect)")
     * @throws IllegalArgumentException if {@code npcName} is {@code null} or
     *                                  blank
     */
    public InterviewScript(String npcId, String npcName, String npcRole) {
        if (npcName == null || npcName.trim().isEmpty()) {
            throw new IllegalArgumentException("npcName must not be blank");
        }
        this.npcId    = npcId   != null ? npcId.trim() : "";
        this.npcName  = npcName.trim();
        this.npcRole  = npcRole != null ? npcRole.trim() : "";
        this.responses = new ArrayList<>();
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    /** Returns the unique identifier for this NPC within the case. */
    public String getNpcId() { return npcId; }

    /** Returns the display name of the NPC being interviewed. */
    public String getNpcName() { return npcName; }

    /** Returns the NPC's role label in the case (e.g. "Key Witness"). */
    public String getNpcRole() { return npcRole; }

    /**
     * Returns an unmodifiable view of all responses in this script.
     */
    public List<InterviewResponse> getResponses() {
        return Collections.unmodifiableList(responses);
    }

    /**
     * Returns all responses matching the given topic.
     *
     * @param topic the topic to filter by; must not be {@code null}
     * @return unmodifiable list of matching responses (may be empty)
     */
    public List<InterviewResponse> getResponsesByTopic(InterviewTopic topic) {
        if (topic == null) return Collections.emptyList();
        return responses.stream()
                .filter(r -> r.getTopic() == topic)
                .collect(Collectors.toList());
    }

    /**
     * Returns all responses that concern a specific other NPC.
     *
     * @param aboutNpcName the name of the NPC the question is about
     * @return unmodifiable list of matching responses (may be empty)
     */
    public List<InterviewResponse> getResponsesAbout(String aboutNpcName) {
        if (aboutNpcName == null || aboutNpcName.isEmpty()) {
            return Collections.emptyList();
        }
        return responses.stream()
                .filter(r -> aboutNpcName.equals(r.getAboutNpcName()))
                .collect(Collectors.toList());
    }

    // -------------------------------------------------------------------------
    // Mutation
    // -------------------------------------------------------------------------

    /**
     * Adds a response to this script.
     *
     * @param response must not be {@code null}
     * @throws IllegalArgumentException if {@code response} is {@code null}
     */
    public void addResponse(InterviewResponse response) {
        if (response == null) {
            throw new IllegalArgumentException("response must not be null");
        }
        responses.add(response);
    }

    /** Returns the total number of responses in this script. */
    public int size() { return responses.size(); }

    @Override
    public String toString() {
        return "InterviewScript{npc='" + npcName + "', role='" + npcRole
                + "', responses=" + responses.size() + '}';
    }
}
