package eb.framework1.investigation;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

/**
 * The complete set of interview responses for one NPC in a case.
 *
 * <p>Each NPC who can be interviewed (i.e. is alive and part of the case)
 * has exactly one {@code InterviewScript} containing pre-generated
 * {@link InterviewResponse} entries covering multiple
 * {@link InterviewTopic}s.
 *
 * <p>The responses are generated by {@link CaseGenerator} based on the
 * NPC's role, personality traits (cooperativeness, honesty, nervousness),
 * and their relationships with other characters in the case.
 *
 * <h3>Example</h3>
 * <pre>
 *   InterviewScript script = new InterviewScript("npc-3", "Helen Davis", "Key Witness");
 *   script.addResponse(new InterviewResponse(
 *       InterviewTopic.ALIBI,
 *       "Where were you on the night of the incident?",
 *       "I was at home all evening. My neighbour can confirm.",
 *       true, ""));
 *   script.addResponse(new InterviewResponse(
 *       InterviewTopic.OPINION,
 *       "What do you think of Robert Smith?",
 *       "He's always been jealous of the victim's success.",
 *       true, "Robert Smith"));
 * </pre>
 */
public final class InterviewScript {

    /** Default reliability score — fully reliable. */
    public static final float DEFAULT_RELIABILITY = 1.0f;

    /** Minimum allowed reliability score. */
    public static final float MIN_RELIABILITY = 0.5f;

    private final String npcId;
    private final String npcName;
    private final String npcRole;
    private final List<InterviewResponse> responses;

    /**
     * How reliable this witness is, on a scale from {@value #MIN_RELIABILITY}
     * (frequently inaccurate) to {@value #DEFAULT_RELIABILITY} (fully
     * truthful).  The score influences how many of the NPC's responses are
     * flagged as truthful at generation time.
     *
     * <p>A value of {@value #DEFAULT_RELIABILITY} means the witness is 100 %
     * reliable (all responses truthful unless the topic inherently involves
     * deception, e.g. a suspect's alibi).  Lower values mean some responses
     * are randomly flipped to non-truthful during interview generation.
     */
    private float reliability;

    /**
     * Creates an empty interview script for the given NPC with default
     * (full) reliability.
     *
     * @param npcId   unique identifier for this NPC within the case
     * @param npcName display name of the NPC being interviewed
     * @param npcRole the NPC's role in the case (e.g. "Key Witness",
     *                "Subject (Suspect)")
     * @throws IllegalArgumentException if {@code npcName} is {@code null} or
     *                                  blank
     */
    public InterviewScript(String npcId, String npcName, String npcRole) {
        this(npcId, npcName, npcRole, DEFAULT_RELIABILITY);
    }

    /**
     * Creates an empty interview script with the specified reliability score.
     *
     * @param npcId       unique identifier for this NPC within the case
     * @param npcName     display name of the NPC being interviewed
     * @param npcRole     the NPC's role in the case
     * @param reliability witness reliability from {@value #MIN_RELIABILITY}
     *                    to {@value #DEFAULT_RELIABILITY}
     * @throws IllegalArgumentException if {@code npcName} is {@code null} or
     *                                  blank, or if {@code reliability} is
     *                                  outside the valid range
     */
    public InterviewScript(String npcId, String npcName, String npcRole,
                           float reliability) {
        if (npcName == null || npcName.trim().isEmpty()) {
            throw new IllegalArgumentException("npcName must not be blank");
        }
        if (reliability < MIN_RELIABILITY || reliability > DEFAULT_RELIABILITY) {
            throw new IllegalArgumentException(
                    "reliability must be between " + MIN_RELIABILITY + " and "
                            + DEFAULT_RELIABILITY + ", got " + reliability);
        }
        this.npcId       = npcId   != null ? npcId.trim() : "";
        this.npcName     = npcName.trim();
        this.npcRole     = npcRole != null ? npcRole.trim() : "";
        this.responses   = new ArrayList<>();
        this.reliability = reliability;
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    /** Returns the unique identifier for this NPC within the case. */
    public String getNpcId() { return npcId; }

    /** Returns the display name of the NPC being interviewed. */
    public String getNpcName() { return npcName; }

    /** Returns the NPC's role label in the case (e.g. "Key Witness"). */
    public String getNpcRole() { return npcRole; }

    /**
     * Returns the witness reliability score.
     *
     * <p>A value of {@value #DEFAULT_RELIABILITY} means fully reliable; lower
     * values (down to {@value #MIN_RELIABILITY}) indicate an unreliable or
     * bribed witness whose testimony may be inaccurate.
     */
    public float getReliability() { return reliability; }

    /**
     * Returns {@code true} if this NPC has less than full reliability.
     */
    public boolean isUnreliable() {
        return reliability < DEFAULT_RELIABILITY;
    }

    /**
     * Returns an unmodifiable view of all responses in this script.
     */
    public List<InterviewResponse> getResponses() {
        return Collections.unmodifiableList(responses);
    }

    /**
     * Returns all responses matching the given topic.
     *
     * @param topic the topic to filter by; must not be {@code null}
     * @return unmodifiable list of matching responses (may be empty)
     */
    public List<InterviewResponse> getResponsesByTopic(InterviewTopic topic) {
        if (topic == null) return Collections.emptyList();
        return responses.stream()
                .filter(r -> r.getTopic() == topic)
                .collect(Collectors.toList());
    }

    /**
     * Returns all responses that concern a specific other NPC.
     *
     * @param aboutNpcName the name of the NPC the question is about
     * @return unmodifiable list of matching responses (may be empty)
     */
    public List<InterviewResponse> getResponsesAbout(String aboutNpcName) {
        if (aboutNpcName == null || aboutNpcName.isEmpty()) {
            return Collections.emptyList();
        }
        return responses.stream()
                .filter(r -> aboutNpcName.equals(r.getAboutNpcName()))
                .collect(Collectors.toList());
    }

    // -------------------------------------------------------------------------
    // Mutation
    // -------------------------------------------------------------------------

    /**
     * Adds a response to this script.
     *
     * @param response must not be {@code null}
     * @throws IllegalArgumentException if {@code response} is {@code null}
     */
    public void addResponse(InterviewResponse response) {
        if (response == null) {
            throw new IllegalArgumentException("response must not be null");
        }
        responses.add(response);
    }

    /** Returns the total number of responses in this script. */
    public int size() { return responses.size(); }

    @Override
    public String toString() {
        return "InterviewScript{npc='" + npcName + "', role='" + npcRole
                + "', reliability=" + reliability
                + ", responses=" + responses.size() + '}';
    }
}
